---
title: "Supplementary Plots"
header-includes:
- \usepackage{booktabs}
# - \usepackage{sectsty} \sectionfont{\centering}
output:
  pdf_document: default
  html_document: default
geometry: top=3.5cm, bottom=3cm

# knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path('plots', 'supplementary.pdf')) })
---


```{r echo = FALSE, warning = FALSE, message = FALSE} 

#-------------------------#
#--------LIBRARIES--------#
#-------------------------#
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(grid)
library(gridExtra)
library(ggpubr)
# library(directlabels)
library(gsubfn)



#-------------------------#
#-----GLOBAL VARIABLES----#
#-------------------------#
project_dir <- getwd()
setwd(project_dir)

source(file.path(project_dir, 'scripts', 'us-common-functions.R'))
``` 

```{r echo=FALSE, warning = FALSE, message = FALSE}
#-------------------------#
#-----GLOBAL FUNCTIONS----#
#-------------------------#
draw_plots <- function() {
  df <- read_csv()
  
  subj_list <- levels(factor(filtered_df$Subject))
  # subj_list <- c('T005', 'T0015')
  # subj_list <- c('T011')
  
  for(subj in subj_list) {
    
    subj_list <- levels(factor(filtered_df$Subject))
    for (session in session_list) {
      
    }
    
  }
}

```



<!-- DRAW PLOTS -->
```{r echo=FALSE, warning = FALSE, message = FALSE}
draw_plots()
```

