---
title: "Linear model"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(grid)
library(gridExtra)
library(ggpubr)
library(DataCombine)
library(reshape2)
library(tidyr)
library(stringr)
library(plyr)
library(ggplot2)
library(dplyr)
library(miceadds)
library(gtools)
library(gvlma)
library(MASS)
library(zoo)
library(sjPlot)
library(sjmisc)
```



```{r, echo=FALSE}

current_dir <- getwd()
setwd('..')
root_dir <- getwd()
data_dir <- file.path(root_dir, 'curated-data/physiological-data')
plot_dir <- file.path(root_dir,'plots/CaseStudy2022')
file_name <- 'Local_min_day_model_data+FACS.csv'
Data <- read.csv(file.path(data_dir,file_name),stringsAsFactors = FALSE)


Data$F_Negarive <- Data$F_Angry + Data$F_Disgusted + Data$F_Afraid + Data$F_Sad


Data <- Data %>% mutate(Day = recode(Day, "Day1" = 1, "Day2" = 2, "Day3" = 3, "Day4" = 4))
Data$Day <- as.factor(Data$Day)
Data$R <- as.factor(Data$R)
Data$G <- as.factor(Data$G)


Data <- subset(Data , select = -c(Participant_ID, Treatment, F_Angry, F_Disgusted, F_Afraid, F_Sad, F_Surprised, F_Binary, FSum_Binary, Out, T_RW_APPS, T_EA, T_PA, T_VC, AB))

write.csv(Data, file.path(data_dir, "model_data.csv"), row.names = FALSE)
```


## Backward Elimination
```{r, echo=FALSE}
# colnames(Data)
NullModel_nasa <- lm(PP ~ 1, data = Data)
FullModel_nasa <- lm(PP ~ ., data = Data)
BEmodel <- stepAIC(FullModel_nasa, direction = "backward", trace = FALSE)
summary(BEmodel)
AIC(BEmodel)
```




\newpage
## Forward Selection
```{r, echo=FALSE}
FSmodel <-step(NullModel_nasa,direction="forward", scope=list(upper=FullModel_nasa, lower=NullModel_nasa), trace = FALSE)
summary(FSmodel)
AIC(FSmodel)
```


\newpage
## Step-Wise method
```{r, echo=FALSE}
SWmodel<-step(NullModel_nasa,scope=list(lower=formula(NullModel_nasa),upper=formula(FullModel_nasa)), direction="both",trace = FALSE)
# SWmodel$anova
summary(SWmodel)
AIC(SWmodel)
```


\newpage
## Final Model
```{r, echo=FALSE}
model_interaction <- lm(formula = PP ~ fOut + RW + R*SP, data = Data)
summary(model_interaction)
```




```{r, echo=FALSE}
model_plot <- function(model_name,type_,  predictor, X_title, y_title) {
  plt = plot_model(model_name, type = type_, terms = predictor) +
    theme_bw() +
    theme(
      panel.grid = element_blank(),
      axis.text.x = element_text(face = "bold", size = 10),
      axis.text.y = element_text(face = "bold", size = 10),
      axis.title=element_text(size=12,face="bold")
    ) +
    labs(y = y_title, x = X_title, title = "")
}






model_plot_int <-
  function(model_name,
           type_,
           predictor,
           X_title,
           y_title) {
    plt = plot_model(model_name, type = type_, terms = predictor) +
      theme_bw() +
      theme(
        panel.grid = element_blank(),
        axis.text.x = element_text(face = "bold", size = 10),
        axis.text.y = element_text(face = "bold", size = 10),
        axis.title = element_text(size = 12, face = "bold")
      ) + scale_color_manual(
        labels = c(
          expression(italic(R1)),
          expression(italic(R2)),
          expression(italic(R3)),
          expression(italic(R4))
        ),
        values = c("green", "blue", "orange", "red")
      ) +
      labs(y = y_title, x = X_title, title = "") +
      theme(legend.position = 'top',
            # legend.spacing.x = unit(0.5, "cm"),
            legend.title = element_blank())
  }



model_plot_G <-
  function(model_name,
           type_,
           predictor,
           X_title,
           y_title) {
    plt = plot_model(model_name, type = type_, terms = predictor) +
      # theme_bw() + 
      scale_x_discrete(labels =c ("1" = "G1", "2" = "G2"))+
      labs(y = y_title, x = X_title, title = "")
  }

```



```{r, echo=FALSE}
y_title = element_blank()
X_title <- expression(italic(f[Out])~paste('[breaks/hour]'))
fout_plot <- model_plot(model_interaction, "pred", "fOut", X_title, y_title)
fout_plot

y_title = expression(Delta~italic("PP"))
X_title <- expression(italic(T[RW])~paste('[ % ]'))
RW_plot <- model_plot(model_interaction, "pred", "RW", X_title, y_title)
RW_plot

y_title= element_blank()
X_title <- expression(italic(T[SP])~paste('[ % ]'))
int_plot <- model_plot_int(model_interaction,"pred",predictor = c("SP","R"), X_title, y_title)
int_plot
# legend_int <- get_legend(int_plot)


final_plot <-
  ggarrange(RW_plot,
            int_plot,
            fout_plot,
            nrow = 1)

# final_plot <- plot_grid(legend_int, final_plot, nrow = 2, rel_heights = c(.07, 1.2))


filename <- "model_plot.pdf"
full_path <- file.path(plot_dir, filename)
ggsave(
  full_path,
  final_plot,
  width = 8.5,
  height = 4,
  units = "in"
)
```



```{r, echo=FALSE}
# current_dir <- getwd()
# setwd('..')
# root_dir <- getwd()
# data_dir <- file.path(root_dir, 'curated-data/physiological-data')
# plot_dir <- file.path(root_dir,'plots/CaseStudy2022')

# normalized_data_file <-'model_df_day_min.csv'
# activity_data_file <- 'Activity_Data.csv'
# questionnaire_data_file <- 'Questionnaire_Data.csv'
# daily_survey_data_file <- 'DailySurveyResults.csv'
# 
# 
# physiologicalData <- read.csv(file.path(data_dir,normalized_data_file),stringsAsFactors = FALSE)
# 
# physiologicalData <- subset(physiologicalData , select = c(Participant_ID, Day, Treatment, T_D, T_WP, T_EM, T_WB, T_EA, T_PA, T_VC, PP, tOut, fOut))
# 
# activityData <- read.csv(file.path(data_dir,activity_data_file),stringsAsFactors = FALSE)
# activityData$RW <- activityData$R + activityData$W
# activityData$R <- NULL
# activityData$W <- NULL
# 
# 
# 
# Q_Data <- read.csv(file.path(data_dir,questionnaire_data_file),stringsAsFactors = FALSE)
# Q_Data <- Q_Data[,-c(1, 4:34, 42:45 )]
# Q_Data$G = c("Male", "Female", "Male", "Female", "Male", "Female", "Female", "Male", "Male", "Male")
# 
# daily_survey_data <- read.csv(file.path(data_dir,daily_survey_data_file),stringsAsFactors = FALSE)
```


```{r, echo=FALSE, warning=FALSE}
# library(corrplot)
# library(superml)
# 
# 
# # rank_factor <- factor(Corelation_DF$Rank)
# # Corelation_DF$Rank <- as.numeric(rank_factor)
# 
# # Corelation_DF$BR<-factor(Corelation_DF$BR)
# cor_activity <- cor(activityData[, c(3:8)], use = "complete.obs")
# res1 <- cor.mtest(activityData[, c(3:8)], conf.level = .95)
# 
# # significance_plot<-
# corrplot(
#   cor_activity,
#   p.mat = res1$p,
#   method = "color",
#   type = "upper",
#   title = "Activity Correlation",
#   sig.level = c(.001, .01, .05),
#   pch.cex = .9,
#   diag = FALSE,
#   insig = "label_sig",
#   pch.col = "black",
#   col = colorRampPalette(c("brown1", "white", "dodgerblue"))(200),
#   tl.col = "black",
#   mar = c(0, 0, 1, 0)
# )



```

<!-- \newpage -->
<!-- ## Probability density of OUT -->
```{r, echo=FALSE}
# out_plot <-
#   ggplot(data = activityData) + geom_density(aes(Out)) + theme_bw() + geom_vline(
#     aes(xintercept = mean(Out)),
#     color = "blue",
#     linetype = "dashed",
#     size = 1
#   )
# print(out_plot)
```




<!-- ```{r, echo=FALSE} -->
<!-- Merged_Data <- merge(x = physiologicalData, y = activityData, by = c("Participant_ID", "Day")) -->
<!-- Merged_Data <- merge(x = Merged_Data, y = daily_survey_data, by = c("Participant_ID", "Day")) -->
<!-- Data <- merge(x = Merged_Data, y = Q_Data, by = "Participant_ID") -->

<!-- Data <- -->
<!--   Data %>%  mutate(G = recode(G, "Male" = 1, "Female" = 2)) %>%  -->
<!--   # mutate(Day = recode(Day, "Day1" = 1, "Day2" = 2, "Day3" = 3, "Day4" = 4)) %>%  -->
<!--   mutate(Position = recode(Position, "PhD Student" = 1, "PhD student" = 1, "Post Doc" = 2, "PostDoc" = 2, "Assistant Professor" = 3, "Professor" = 4)) -->




<!-- names(Data)[names(Data) == 'Position'] <- 'R' -->



<!-- Data$T_RW_APPS <- Data$T_WP + Data$T_EM + Data$T_WB -->

<!-- Data <- -->
<!--   dplyr::select( -->
<!--     Data, -->
<!--     Participant_ID, -->
<!--     Day, -->
<!--     Treatment, -->
<!--     PP, -->
<!--     G, -->
<!--     R, -->
<!--     TA, -->
<!--     B5_A, -->
<!--     B5_C, -->
<!--     B5_E, -->
<!--     B5_N, -->
<!--     B5_O, -->
<!--     AB, -->
<!--     Day, -->
<!--     T_D, -->
<!--     SA_B, -->
<!--     SA_E, -->
<!--     N_MD, -->
<!--     N_PD, -->
<!--     N_TD, -->
<!--     N_P, -->
<!--     N_E, -->
<!--     N_F, -->
<!--     RW, -->
<!--     SA, -->
<!--     SP, -->
<!--     Out, -->
<!--     I, -->
<!--     # MT, -->
<!--     tOut, -->
<!--     fOut, -->
<!--     # T_WP, -->
<!--     # T_EM, -->
<!--     T_RW_APPS, -->
<!--     # T_WB, -->
<!--     T_EA, -->
<!--     T_PA, -->
<!--     T_VC -->
<!--   ) -->

<!-- # write.csv(Data, file.path(data_dir, "Global_min_day_model_data.csv"), row.names = FALSE) -->

<!-- Data$G <- as.factor(Data$G) -->
<!-- Data$R <- as.factor(Data$R) -->


<!-- Data <- Data %>% mutate(Day = recode(Day, "Day1" = 1, "Day2" = 2, "Day3" = 3, "Day4" = 4)) -->
<!-- Data$Day <- as.factor(Data$Day) -->
<!-- Data <- subset(Data , select = -c(Participant_ID, Treatment)) -->
<!-- Data <- Data[complete.cases(Data),] -->


<!-- ``` -->



```{r,echo=FALSE}
# cor_activity <- cor(Data, use = "complete.obs")
# res1 <- cor.mtest(Data, conf.level = .95)
# 
# # significance_plot<-
# corrplot(
#   cor_activity,
#   p.mat = res1$p,
#   method = "color",
#   type = "upper",
#   title = "Activity Correlation",
#   sig.level = c(.001, .01, .05),
#   pch.cex = .9,
#   diag = FALSE,
#   insig = "label_sig",
#   pch.col = "black",
#   col = colorRampPalette(c("brown1", "white", "dodgerblue"))(200),
#   tl.col = "black",
#   mar = c(0, 0, 1, 0)
# )
```


```{r, echo=FALSE}
# fit1 <- lm(y ~ ., data)
# fit2 <- lm(y ~ 1, data)
# stepAIC(fit1,direction="backward")
# 
# stepAIC(fit2,direction="forward",scope=list(upper=fit1,lower=fit2))
# stepAIC(fit2,direction="both",scope=list(upper=fit1,lower=fit2))
```

<!-- ## Backward Elimination -->
<!-- ```{r, echo=FALSE} -->
<!-- NullModel <- lm(PP ~ 1, data = Data) -->
<!-- FullModel <- lm(PP ~ ., data = Data) -->
<!-- BEmodel <- stepAIC(FullModel, direction = "backward", trace = FALSE) -->
<!-- summary(BEmodel) -->
<!-- AIC(BEmodel) -->
<!-- # plot_model(BEmodel, type = "pred") -->
<!-- # BEmodel$anova -->
<!-- ``` -->




<!-- \newpage -->
<!-- ## Optimized Backward Elimination -->
<!-- ```{r, echo=FALSE} -->
<!-- BE_optimaization <- lm(formula = PP ~ Day + G + R + TA + B5_A + B5_N + SA_B + N_MD + N_TD + fOut, data = Data) -->
<!-- summary(BE_optimaization) -->
<!-- AIC(BE_optimaization) -->
<!-- ``` -->




```{r, echo=FALSE}
## Removed WP, EM, N_PD, N_TD, N_F, B5_N
# BE_optimaization <- lm(formula = PP ~ Day + DL + EA + VC + Out + SP + N_MD + N_P + R + TA + AB + B5_A +
#     B5_C + B5_E, data = Data)
# summary(BE_optimaization)
# plot_model(BE_optimaization, type = "pred")
```




<!-- \newpage -->
<!-- ## Forward Selection -->
<!-- ```{r, echo=FALSE} -->
<!-- FSmodel <-step(NullModel,direction="forward", scope=list(upper=FullModel, lower=NullModel), trace = FALSE) -->
<!-- summary(FSmodel) -->
<!-- AIC(FSmodel) -->
<!-- ``` -->







<!-- \newpage -->
<!-- ## Step-Wise method -->
<!-- ```{r, echo=FALSE} -->
<!-- SWmodel<-step(NullModel,scope=list(lower=formula(NullModel),upper=formula(FullModel)), direction="both",trace = FALSE) -->
<!-- # SWmodel$anova -->
<!-- summary(SWmodel) -->
<!-- AIC(SWmodel) -->
<!-- ``` -->

<!-- \newpage -->
<!-- ## Common significant predictors in all models -->
<!-- ```{r, echo=FALSE} -->

<!-- best_model <- lm(formula = PP ~ G + R + Day + fOut  + SA_B + B5_N + B5_A + N_TD + N_MD + TA, data = Data) -->
<!-- summary(best_model) -->
<!-- AIC(best_model) -->

<!-- # plot_model(best_model, type = "pred") -->
<!-- ``` -->



<!-- \newpage -->
<!-- # NASA Performance model -->
<!-- ## Backward Elimination -->
<!-- ```{r, echo=FALSE} -->
<!-- # colnames(Data) -->
<!-- NullModel_nasa <- lm(N_P ~ 1, data = Data) -->
<!-- FullModel_nasa <- lm(N_P ~ ., data = Data) -->
<!-- BEmodel <- stepAIC(FullModel_nasa, direction = "backward", trace = FALSE) -->
<!-- summary(BEmodel) -->
<!-- AIC(BEmodel) -->
<!-- ``` -->


<!-- \newpage -->
<!-- ## NASA Optimized -->
<!-- ```{r, echo=FALSE} -->
<!-- OP_BW <- lm(formula = N_P ~ Day + PP + G + R + TA + B5_A + B5_C + B5_E + B5_N + N_MD + N_F + T_RW_APPS +  -->
<!--     T_EA + T_PA + T_VC, data = Data) -->
<!-- summary(OP_BW) -->
<!-- AIC(OP_BW) -->
<!-- ``` -->




<!-- \newpage -->
<!-- ## Forward Selection -->
<!-- ```{r, echo=FALSE} -->
<!-- FSmodel <-step(NullModel_nasa,direction="forward", scope=list(upper=FullModel_nasa, lower=NullModel_nasa), trace = FALSE) -->
<!-- summary(FSmodel) -->
<!-- AIC(FSmodel) -->
<!-- ``` -->

<!-- \newpage -->
<!-- ## Step-Wise method -->
<!-- ```{r, echo=FALSE} -->
<!-- SWmodel<-step(NullModel_nasa,scope=list(lower=formula(NullModel_nasa),upper=formula(FullModel_nasa)), direction="both",trace = FALSE) -->
<!-- # SWmodel$anova -->
<!-- summary(SWmodel) -->
<!-- AIC(SWmodel) -->
<!-- ``` -->

<!-- \newpage -->






<!-- \newpage -->
<!-- ## Nasa performance model -->
<!-- ```{r, echo=FALSE} -->
<!-- NullModel_nasa <- lm(N_P ~ 1, data = Data) -->
<!-- FullModel_nasa <- lm(N_P ~ ., data = Data) -->
<!-- BEmodel <- stepAIC(FullModel_nasa, direction = "backward", trace = FALSE) -->
<!-- summary(BEmodel) -->
<!-- AIC(BEmodel) -->
<!-- ``` -->


<!-- \newpage -->
<!-- ## NASA Optimized model -->
<!-- ```{r, echo=FALSE} -->
<!-- nasa_op <- lm(formula = N_P ~  I + G, data = Data) -->
<!-- summary(nasa_op) -->
<!-- AIC(nasa_op) -->




<!-- Zcrit<-1.96   ### critical value for 95% confidence intervals -->

<!-- ilink <- family(nasa_op)$linkinv -->

<!-- G<-c("1","2",rep("1",1)) -->
<!-- I<-rep(7.528536,1) -->


<!-- tmpd<-data.frame(G, I) -->
<!-- ndata <- cbind(tmpd, setNames(as_tibble(predict(nasa_op, tmpd, se.fit = TRUE)[1:2]), -->
<!--                                    c('fit_link','se_link'))) -->
<!-- Model_Nasa_performance <- mutate(ndata, -->
<!--                 fit_resp  = ilink(fit_link), -->
<!--                 Lower_limit = ilink(fit_link - (Zcrit * se_link)), -->
<!--                 Upper_limit = ilink(fit_link + (Zcrit * se_link))) -->
<!-- Model_Nasa_performance <- slice(Model_Nasa_performance, 1:(n() - 1)) -->



<!-- plot <- -->
<!--   ggplot(Model_Nasa_performance, aes(x = G, y = fit_resp)) + -->
<!--   geom_pointrange(aes(ymin = Lower_limit, ymax = Upper_limit)) + -->
<!--   theme_bw() + -->
<!--   theme( -->
<!--     panel.grid = element_blank(), -->
<!--     axis.text.x = element_text(face = "bold", size = 10), -->
<!--     axis.text.y = element_text(face = "bold", size = 10), -->
<!--     axis.ticks.y = element_blank(), -->
<!--     axis.ticks.x = element_blank() -->
<!--   ) + -->
<!--   scale_x_discrete(labels = c ("1" = "G1", "2" = "G2")) + -->
<!--   labs(y = "", x = expression(italic(G)), title = "") + ylim(1, 20) -->

<!-- plot -->




<!-- y_title = expression(italic(N[P])) -->
<!-- X_title <- expression(italic(T[I])~paste('[ % ]')) -->
<!-- Int_plot <- model_plot(nasa_op, "pred", "I", X_title, y_title) -->
<!-- Int_plot <- Int_plot + ylim(1, 20)  -->

<!-- Int_plot -->





<!-- final_plot_nasa <- -->
<!--   plot_grid(Int_plot, plot, -->
<!--             nrow = 1) -->

<!-- filename <- "model_plot_nasa.pdf" -->
<!-- full_path <- file.path(plot_dir, filename) -->
<!-- ggsave( -->
<!--   full_path, -->
<!--   final_plot_nasa, -->
<!--   width = 8.5, -->
<!--   height = 4, -->
<!--   units = "in" -->
<!-- ) -->

<!-- ``` -->


<!-- \newpage -->
<!-- ## Forward Selection -->
<!-- ```{r, echo=FALSE} -->
<!-- FSmodel <-step(NullModel_nasa,direction="forward", scope=list(upper=FullModel_nasa, lower=NullModel_nasa), trace = FALSE) -->
<!-- summary(FSmodel) -->
<!-- AIC(FSmodel) -->
<!-- ``` -->

<!-- \newpage -->
<!-- ## Step-Wise method -->
<!-- ```{r, echo=FALSE} -->
<!-- SWmodel<-step(NullModel_nasa,scope=list(lower=formula(NullModel_nasa),upper=formula(FullModel_nasa)), direction="both",trace = FALSE) -->
<!-- # SWmodel$anova -->
<!-- summary(SWmodel) -->
<!-- AIC(SWmodel) -->
<!-- ``` -->