<<<<<<< HEAD
---
title: "Ontologies"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
current_dir <- getwd()
setwd('..')
root_dir <- getwd()
data_dir <- file.path(root_dir, 'curated-data/physiological-data')
data_file_name<-'quantitative_df_qc0.csv'
```


```{r cars, echo=FALSE}
DF<-read.csv(file.path(data_dir,data_file_name))

```


```{r, echo=FALSE}
Plot1<-function(fun.data, fun.x, Day, SID, title,y_max ){
p<-ggplot(fun.data, aes(x=fun.x)) + 
  geom_bar(stat="count", width=0.5)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ylab("Seconds")+
  xlab("")+
  labs(title =title )+
  theme(plot.title = element_text(hjust = 0.5))
 return(p)
 
}
```


```{r, echo=FALSE}
sid<-factor(DF$Participant_ID)
n=nlevels(sid)
for (i in 1:n) {
  DF_T001<-subset(DF, Participant_ID==levels(sid)[i] & Treatment=="WS")
  D_id<-factor(DF_T001$Day)
  m=nlevels(D_id)
  for (j in 1:m) {
    
    DF_S_D<-subset(DF_T001, Day==levels(D_id)[j])
    title=paste(levels(sid)[i],levels(D_id)[j])
    y_max=max(DF_S_D$Time)
    print(Plot1(DF_S_D,  DF_S_D$Ontologies, DF_S_D$Day,DF_S_D$Participant_ID, title, y_max))
  }
}
```
=======
---
title: "Ontologies"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(ggpubr)
#install.packages('DataCombine')
library(DataCombine)
library(dplyr)
library(reshape2)
library(tidyr)
library(stringr)
library(plyr)
library(ggplot2)
library(dplyr)
library(miceadds)
library(gtools)
library(ggpubr)
library(gvlma)
library(MASS)
library(reshape2)
library(ggcorrplot)
library(GGally)
library(ggnewscale)
library(scales)
current_dir <- getwd()
setwd('..')
root_dir <- getwd()
data_dir <- file.path(root_dir, 'curated-data/physiological-data')
data_file_name<-'qc99_all_subj.csv'
```


```{r cars, echo=FALSE}
DF<-read.csv(file.path(data_dir,data_file_name),stringsAsFactors = FALSE)
file_name <- 'Quantitive_All_subject.csv'
DF<-DF[!(DF$Participant_ID=="T005" & DF$Day=="Day4"),]
DF$Day[DF$Day=="Day5"] <- "Day4"



Subject_id<-factor(DF$Participant_ID)
Number_of_subjects=nlevels(Subject_id)
for (i in 1:Number_of_subjects) {
  DF_T001<-subset(DF, Participant_ID==levels(Subject_id)[i])
  Sub_file_name<-paste0(levels(Subject_id)[i],".csv")
  convert_to_csv(DF_T001, file.path(root_dir,curated_data_dir, physiological_data_dir, Sub_file_name))
}


convert_to_csv(DF, file.path(root_dir,curated_data_dir, physiological_data_dir, file_name))
```


<!--```{r, echo=FALSE}
DF$Activities1<-DF$Activities
DF<-DF %>%
  separate(Activities1, c("A", "B", "C"), ",")
DF$A<-trimws(DF$A)
DF$B<-trimws(DF$B)


if (is.na(DF$C)!=TRUE) {
  DF$C<-trimws(DF$c)
}


#unique(DF$A)
DF$A<-gsub("\\(|\\)", "", DF$A)
DF$B<-gsub("\\(|\\)", "", DF$B)
DF$C<-gsub("\\(|\\)", "", DF$C)


Out='Break Out|Break Out - Other|Break - Out|Break Out - Tea/Coffee|Break Out -Other|Break Out - - Tea/Coffee|Out'
CR='^C - Reading$|Computer - Reading|Computer Reading CR'
CW='^C - Writing$/Reading|C - Writing|^Computer - Reading and Writing$|Computer - Writing|Computer Writing CW'
EiP='^Break In - Meal$|Break In Place - Tea/Coffee|Break In Place - Meal|Eat in Place EiP'
OB='^Break In - Other$|^Other Break OB$|Break In Place - Other'
Working='Working'
Thinking='Thinking|Thinking T'
SP='SP - Talking|SP - Looking|SmartPhone - Looking|SmartPhone - Talking|Smart Phone SP'
PR='^HC - Reading$|Hard Copy - Reading'
PW='^HC - Writing$|Hard Copy - Writing|^Board Writing$|^Board Writing BW$'
ELD='Listening on Headphone'
PI='H-H Interaction|Personal Interaction PI|Physical Interaction PI'
VI='C - Talking Skype & others|Virtual Interaction VI'

                          
                           DF$A<-case_when(str_detect(DF$A, Out)~"Out",
                                                      str_detect(DF$A, PW)~"PW",
                                                      str_detect(DF$A, PR)~"PR",
                                                      str_detect(DF$A, CW)~"CW",
                                                      str_detect(DF$A, CR)~"CR",
                                                      str_detect(DF$A, EiP)~"EiP",
                                                      str_detect(DF$A, OB)~"OB",
                                                      str_detect(DF$A, Working)~"Working",
                                                      str_detect(DF$A, Thinking)~"T",
                                                      str_detect(DF$A, SP)~"SP",
                                                      str_detect(DF$A, ELD)~"ELD",
                                                      str_detect(DF$A, PI)~"PI", 
                                                      str_detect(DF$A, VI)~"VI"
                                                      
                                                      )
                            DF$B<-case_when(str_detect(DF$B, Out)~"Out",
                                                      str_detect(DF$B, PW)~"PW",
                                                      str_detect(DF$B, PR)~"PR",
                                                      str_detect(DF$B, CW)~"CW",
                                                      str_detect(DF$B, CR)~"CR",
                                                      str_detect(DF$B, EiP)~"EiP",
                                                      str_detect(DF$B, OB)~"OB",
                                                      str_detect(DF$B, Working)~"Working",
                                                      str_detect(DF$B, Thinking)~"T",
                                                      str_detect(DF$B, SP)~"SP",
                                                      str_detect(DF$B, ELD)~"ELD",
                                                      str_detect(DF$B, PI)~"PI",
                                                      str_detect(DF$B, VI)~"VI"
                                                      )
                            DF$C<-case_when(str_detect(DF$C, Out)~"Out",
                                                      str_detect(DF$C, PW)~"PW",
                                                      str_detect(DF$C, PR)~"PR",
                                                      str_detect(DF$C, CW)~"CW",
                                                      str_detect(DF$C, CR)~"CR",
                                                      str_detect(DF$C, EiP)~"EiP",
                                                      str_detect(DF$C, OB)~"OB",
                                                      str_detect(DF$C, Working)~"Working",
                                                      str_detect(DF$C, Thinking)~"T",
                                                      str_detect(DF$C, SP)~"SP",
                                                      str_detect(DF$C, ELD)~"ELD",
                                                      str_detect(DF$C, PI)~"PI",
                                                      str_detect(DF$C, VI)~"VI"
                                                      )
DF$C[is.na(DF$C)] <- ""
DF$B[is.na(DF$B)] <- ""
DF$D<-paste(DF$A,DF$B,DF$C, sep="+")
DF<-DF%>%
    mutate(D1=gsub("(\\+)*$", "", D))

# unique(DF$Activities)
# unique(DF$D1)
DF$Activities_QC1<-DF$D1
# write.csv(DF,'Ontologies.csv')
```-->

```{r, echo=FALSE}
Plot1<-function(fun.data, fun.x, Day, SID, title,y_max ){
p<-ggplot(fun.data, aes(x=fun.x)) + 
  geom_bar(stat="count", width=.5)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1))+
  ylab("Time [s]")+
  xlab("")+
  labs(title =title )+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(breaks = seq(0,y_max, 2500))+
  expand_limits(y=y_max)+
  scale_x_discrete(limits=c( "CR", "CW", "EiP", "OB", "T", "SP", "PR", "PW", "ELD", "PI", "VI","Out", "NA" ))
 return(p)
 
}
```

```{r, echo=FALSE}
Plot2<-function(fun.data, fun.x, Day, SID, title,y_max ){
p<-ggplot(fun.data, aes(x=fun.x)) + 
  geom_bar(stat="count", width=.1)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1))+
  ylab("Time [s]")+
  xlab("")+
  labs(title =title )+
  scale_y_continuous(breaks = seq(0,y_max, 2500))+
   expand_limits(y=y_max)+
  theme(plot.title = element_text(hjust = 0.5))
 return(p)
 
}
```

```{r, echo=FALSE}
## Histogram for all subject both single and multy task.

plot_list<-list()
sid<-factor(DF$Participant_ID)
n=nlevels(sid)
for (i in 1:n) {
  DF_T001<-subset(DF, Participant_ID==levels(sid)[i] & DF$Treatment=="WS")
  D_id<-factor(DF_T001$Day)
  m=nlevels(D_id)
  for (j in 1:m) {
    DF_Sub_Day<-subset(DF_T001, Day==levels(D_id)[j])
    title=paste(levels(sid)[i],levels(D_id)[j], "Single Tasks")
    
    
    #if(title!="T005 Day4 Single Tasks"){
      DF_S_D <- grepl.sub(data = DF_Sub_Day, pattern = ",", Var = "Activities", keep.found = FALSE)
      tab <- table(DF_S_D$Activities_QC1)
      DF_S_D<-DF_S_D[DF_S_D$Activities_QC1 %in% names(tab)[tab>60],]

      y_max=max(DF_S_D$Sinterface_Time)+100
      fig<-Plot1(DF_S_D,  DF_S_D$Activities_QC1, DF_S_D$Day,DF_S_D$Participant_ID, title, y_max)
      print(fig)
      plot_list[[length(plot_list) + 1]] <- fig
      
      title=paste(levels(sid)[i],levels(D_id)[j], "Multi Tasks")
      DF_S_D <- grepl.sub(data = DF_Sub_Day, pattern = ",", Var = "Activities")
      tab <- table(DF_S_D$Activities_QC1)
      DF_S_D<-DF_S_D[DF_S_D$Activities_QC1 %in% names(tab)[tab>60],]

      #y_max=max(DF_S_D$Time)
      fig<-Plot2(DF_S_D,  DF_S_D$Activities_QC1, DF_S_D$Day,DF_S_D$Participant_ID, title, y_max)
      print(fig)
      plot_list[[length(plot_list) + 1]] <- fig
    #}
  }
}

#ggarrange(plotlist = plot_list, nrow = 4, ncol = 2,heights= c(3,3), align = c("hv"))
```


<!--```{r, echo=FALSE}
## First version of heatmap for single subject.
X<-c("CR", "CW", "EiP", "SP", "PR", "ELD", "PI", "VI","Out")
DF_Sub_Day<-subset(DF, Participant_ID=="T011" & Day=="Day2" & Treatment=="WS")
#write.csv(DF_Sub_Day,'T009_Day2.csv')
DF_Sub_Day$Onto_sep<-DF_Sub_Day$Activities_QC1

DF_Sub_Day<-DF_Sub_Day %>% separate(Onto_sep, c("A", "B"))


  for (i in 1:nrow(DF_Sub_Day)){
    
    if(is.na(DF_Sub_Day$B[i])){
      DF_Sub_Day$B[i]<-DF_Sub_Day$A[i]
    }
    
  }

#write.csv(DF_Sub_Day, 'ontology.csv')

mytable<-as.data.frame(table(DF_Sub_Day$A, DF_Sub_Day$B))
colnames(mytable)<-c("A", "B", "Time")
mytable<-subset(mytable, Time>0)

mytable$A<-as.character(mytable$A)
mytable$B<-as.character(mytable$B)
mytable<-mytable[!(mytable$A=="NA" | mytable$A=="Working" | mytable$A=="T" | mytable$A=="PW"),]

mytable_Sym <- data.frame(A = c(mytable[,"A"], mytable[,"B"]),
                          B = c(mytable[,"B"], mytable[,"A"]),
                          Time = c(mytable[,"Time"], mytable[,"Time"]))
mytable_Sym$A<-as.factor(mytable_Sym$A)
mytable_Sym$B<-as.factor(mytable_Sym$B)


rest_of_ontologies<-data.frame(A=setdiff(levels(factor(X)),levels(factor(mytable_Sym$A))),
                       B=setdiff(levels(factor(X)),levels(factor(mytable_Sym$A))),
                       Time=0)

mytable_Sym<-rbind(mytable_Sym, rest_of_ontologies)
mytable_Sym<-mytable_Sym[!(mytable_Sym$A=="OB"),]
#mytable_Sym <- melt(mytable_Sym,na.rm = TRUE)
#mytable_mat<-as.matrix(sapply(mytable, as.numeric))
#mytable_mat<-spread(mytable, B, Time,fill = NA, drop = FALSE)

mytable_mat<-acast(mytable_Sym, A~B, value.var='Time', fun.aggregate=mean)
        mytable_mat <- mytable_mat[, order(colnames(mytable_mat))]
        mytable_mat <- mytable_mat[order(rownames(mytable_mat)),]

# row.names(mytable_mat)<-mytable_mat$A
# mytable_mat$A<-NULL
#mytable_mat[lower.tri(mytable_mat)] <- NA
#main_mat<-main_mat+ mytable_mat

mytable_mat[lower.tri(mytable_mat)] <- NA
mytable_mat[is.nan(mytable_mat)] <- 0

mat <- melt(mytable_mat,na.rm = TRUE)

mat$Var1<-as.character(mat$Var1)
mat$Var2<-as.character(mat$Var2)
mat$value<-(mat$value)/1000
mat$value<-round(mat$value, 1)

mat[is.na(mat)] <- "NA"

order_of_ontology=sort(rownames(mytable_mat))
        
        max_val=max(mat$value)
        min_val=min(mat$value)
        avg_val=mean(mat$value)

        
        p<-ggplot(data = mat, aes(Var1,Var2, fill = value, label=value))+
          geom_tile(color = "black")+
          geom_text(col="black", size=1.5)+
          scale_fill_gradientn(limit = c(0, max_val),
                         colours = c("gray99","yellow","red"))+
          #scale_fill_gradient2(low = "white", high = "red", mid = "white",midpoint = avg_val, limit = c(min_val,max_val), space = "Lab",name="Time") +
          #theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1))+
          theme_classic()+
          theme(axis.text.x = element_text(angle = 45, size = 8,hjust = 1))+
          theme(axis.text.y = element_text(hjust = 1, size = 8))+
          scale_x_discrete(limits=order_of_ontology)+
          scale_y_discrete(limits=order_of_ontology)+
          labs(title=title)+
          ylab("")+
          xlab("")+
          theme(panel.background = element_blank(),
          panel.grid = element_blank()) +
          labs(fill="Time [s]*1000")+
          theme(plot.title = element_text(hjust = 0.5))
          #theme(plot.title = element_text(hjust = 0.5))
        print(p)


#X<-c("CR", "CW", "EiP", "T", "SP", "PR", "PW", "ELD", "PI", "VI","Out")
```-->


<!--```{r, echo=FALSE}
## First version of heatmap for all subjects.

X<-c("CR", "CW", "EiP", "T", "SP", "PR", "PW", "ELD", "PI", "VI","Out")
plot_list_heatmap<-list()
sid<-factor(DF$Participant_ID)
n=nlevels(sid)
for (i in 1:n) {
  DF_T001<-subset(DF, Participant_ID==levels(sid)[i] & DF$Treatment=="WS")
  D_id<-factor(DF_T001$Day)
  m=nlevels(D_id)
  for (j in 1:m) {
    DF_Sub_Day<-subset(DF_T001, Day==levels(D_id)[j])
    
    title=paste(levels(sid)[i],levels(D_id)[j])
    
    #if(title!="T005 Day4"){
    DF_Sub_Day$Onto_sep<-DF_Sub_Day$Activities_QC1
    DF_Sub_Day<-DF_Sub_Day %>% separate(Onto_sep, c("A", "B"))
    
    for (k in 1:nrow(DF_Sub_Day)){
      if(is.na(DF_Sub_Day$B[k])){
        DF_Sub_Day$B[k]<-DF_Sub_Day$A[k]
      }
    }
      mytable<-as.data.frame(table(DF_Sub_Day$A, DF_Sub_Day$B))
      colnames(mytable)<-c("A", "B", "Time")
      mytable<-subset(mytable, Time>0)
      
      mytable$A<-as.character(mytable$A)
      mytable$B<-as.character(mytable$B)
      mytable<-mytable[!(mytable$A=="NA" | mytable$A=="Working"),]
      
      mytable_Sym <- data.frame(A = c(mytable[,"A"], mytable[,"B"]),
                                B = c(mytable[,"B"], mytable[,"A"]),
                                Time = c(mytable[,"Time"], mytable[,"Time"]))
      mytable_Sym$A<-as.factor(mytable_Sym$A)
      mytable_Sym$B<-as.factor(mytable_Sym$B)
      
      
      rest_of_ontologies<-data.frame(A=setdiff(levels(factor(X)),levels(factor(mytable_Sym$A))),
                       B=setdiff(levels(factor(X)),levels(factor(mytable_Sym$A))),
                       Time=0) 

        mytable_Sym<-rbind(mytable_Sym, rest_of_ontologies)
        mytable_Sym<-mytable_Sym[!(mytable_Sym$A=="OB"),]
        mytable_mat<-acast(mytable_Sym, A~B, value.var='Time', fun.aggregate=mean)
        mytable_mat <- mytable_mat[, order(colnames(mytable_mat))]
        mytable_mat <- mytable_mat[order(rownames(mytable_mat)),]

        
        
        mytable_mat[lower.tri(mytable_mat)] <- NA
        mytable_mat[is.nan(mytable_mat)] <- 0
        mat <- melt(mytable_mat,na.rm = TRUE)
        
        mat$Var1<-as.character(mat$Var1)
        mat$Var2<-as.character(mat$Var2)
        mat$value<-(mat$value)/1000
        mat$value<-round(mat$value, 1)
        mat[is.na(mat)] <- "NA"
        
        max_val=max(mat$value)
        min_val=min(mat$value)
        avg_val=mean(mat$value)
        
        order_of_ontology<-as.vector(sort(rownames(mytable_mat)))
        
        
        
        p<-ggplot(data = mat, aes(Var1,Var2, fill = value, label=value))+
          geom_tile(color = "black")+
          geom_text(col="black", size=1.5)+
          scale_fill_gradientn(limit = c(0, max_val),
                         colours = c("gray99","yellow","red"))+
          #scale_fill_gradient2(low = "white", high = "red", mid = "white",midpoint = avg_val, limit = c(min_val,max_val), space = "Lab",name="Time") +
          #theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1))+
          theme_classic()+
          theme(axis.text.x = element_text(angle = 45, size = 8,hjust = 1))+
          theme(axis.text.y = element_text(hjust = 1, size = 8))+
          scale_x_discrete(limits=order_of_ontology)+
          scale_y_discrete(limits=order_of_ontology)+
          labs(title=title)+
          ylab("")+
          xlab("")+
          theme(panel.background = element_blank(),
          panel.grid = element_blank()) +
          labs(fill="Time [s]*1000")+
          theme(plot.title = element_text(hjust = 0.5))
          #theme(plot.title = element_text(hjust = 0.5))
        print(p)
        plot_list_heatmap[[length(plot_list_heatmap) + 1]] <- p
      #}
    }
  }
#ggarrange(plotlist = plot_list_heatmap, nrow = 4, ncol = 2,heights= c(3,3), align = c("hv"))

```-->



<!--```{r, echo=FALSE}

X<-c("CR", "CW", "EiP", "SP", "PR", "ELD", "PI", "VI","Out")
plot_list_heatmap<-list()
sid<-factor(DF$Participant_ID)
n=nlevels(sid)
for (i in 1:n) {
  DF_T001<-subset(DF, Participant_ID==levels(sid)[i] & DF$Treatment=="WS")
  D_id<-factor(DF_T001$Day)
  m=nlevels(D_id)
  for (j in 1:m) {
    DF_Sub_Day<-subset(DF_T001, Day==levels(D_id)[j])
    
    title=paste(levels(sid)[i],levels(D_id)[j])
    
    if(title!="T005 Day4"){
    DF_Sub_Day$Onto_sep<-DF_Sub_Day$Activities_QC1
    DF_Sub_Day<-DF_Sub_Day %>% separate(Onto_sep, c("A", "B"))
    
    for (k in 1:nrow(DF_Sub_Day)){
      if(is.na(DF_Sub_Day$B[k])){
        DF_Sub_Day$B[k]<-DF_Sub_Day$A[k]
      }
    }
      mytable<-as.data.frame(table(DF_Sub_Day$A, DF_Sub_Day$B))
      colnames(mytable)<-c("A", "B", "Time")
      mytable<-subset(mytable, Time>0)
      
      mytable$A<-as.character(mytable$A)
      mytable$B<-as.character(mytable$B)
      mytable<-mytable[!(mytable$A=="NA" | mytable$A=="Working"),]
      
      mytable_Sym <- data.frame(A = c(mytable[,"A"], mytable[,"B"]),
                                B = c(mytable[,"B"], mytable[,"A"]),
                                Time = c(mytable[,"Time"], mytable[,"Time"]))
      mytable_Sym$A<-as.factor(mytable_Sym$A)
      mytable_Sym$B<-as.factor(mytable_Sym$B)
      
      
      rest_of_ontologies<-data.frame(A=setdiff(levels(factor(X)),levels(factor(mytable_Sym$A))),
                       B=setdiff(levels(factor(X)),levels(factor(mytable_Sym$A))),
                       Time=0) 

        mytable_Sym<-rbind(mytable_Sym, rest_of_ontologies)
        mytable_Sym<-mytable_Sym[!(mytable_Sym$A=="OB" | mytable_Sym$A=="T" | mytable_Sym$A=="PW"),]
        mytable_mat<-acast(mytable_Sym, A~B, value.var='Time', fun.aggregate=mean)
        mytable_mat <- mytable_mat[, order(colnames(mytable_mat))]
        mytable_mat <- mytable_mat[order(rownames(mytable_mat)),]

        
        
        mytable_mat[lower.tri(mytable_mat)] <- NA
        mytable_mat[is.nan(mytable_mat)] <- 0
        mat <- melt(mytable_mat,na.rm = TRUE)
        
        mat$Var1<-as.character(mat$Var1)
        mat$Var2<-as.character(mat$Var2)
        mat$value<-(mat$value)/1000
        mat$value<-round(mat$value, 1)
        mat[is.na(mat)] <- "NA"
        
        max_val=max(mat$value)
        min_val=min(mat$value)
        avg_val=mean(mat$value)
        
        order_of_ontology<-as.vector(sort(rownames(mytable_mat)))
        
        
        
        p<-ggplot(data = mat, aes(Var1,Var2, fill = value, label=value))+
          geom_tile(color = "black")+
          geom_text(col="black", size=1.5)+
          scale_fill_gradientn(limit = c(0, max_val),
                         colours = c("gray99","yellow","red"))+
          #scale_fill_gradient2(low = "white", high = "red", mid = "white",midpoint = avg_val, limit = c(min_val,max_val), space = "Lab",name="Time") +
          #theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1))+
          theme_classic()+
          theme(axis.text.x = element_text(angle = 45, size = 8,hjust = 1))+
          theme(axis.text.y = element_text(hjust = 1, size = 8))+
          scale_x_discrete(limits=order_of_ontology)+
          scale_y_discrete(limits=order_of_ontology)+
          labs(title=title)+
          ylab("")+
          xlab("")+
          theme(panel.background = element_blank(),
          panel.grid = element_blank()) +
          labs(fill="Time [s]*1000")+
          theme(plot.title = element_text(hjust = 0.5))
          #theme(plot.title = element_text(hjust = 0.5))
        print(p)
        plot_list_heatmap[[length(plot_list_heatmap) + 1]] <- p
      } 
    }
  }
#ggarrange(plotlist = plot_list_heatmap, nrow = 4, ncol = 2,heights= c(3,3), align = c("hv"))
```-->


```{r}
DF_Single<- grepl.sub(data = DF, pattern = ",", Var = "Activities", keep.found = FALSE)

# DF_without_T005<-subset(DF_Single, Participant_ID!="T005")
#DF_with_T005<-subset(DF, Participant_ID =="T005"& Day=="Day4")
# DF_with_T005<-subset(DF_with_T005, DF_with_T005$Day!="Day4")
# 
# 
# DF_without_T005<-rbind(DF_without_T005, DF_with_T005)
#unique(DF_Single$Activities_QC1)
y_max=max(DF_Single$Sinterface_Time)+10000
p1<-ggplot(DF_Single, aes(x=Activities_QC1)) + 
  geom_histogram(stat="count", width=.5)+
  #geom_density()+
  theme(axis.text.x = element_text(angle = 30, hjust = 1))+
  ylab("Time [s]")+
  xlab("")+
  #scale_y_continuous(limits = c(0, max(DF_Single$Sinterface_Time)))
  #scale_y_continuous(limits =  c(0,y_max))+
  #expand_limits(y=y_max)+
  #ylim(0,100000)+
  labs(title ="Single Ontologies For all Subject" )+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_x_discrete(limits=c("CW", "CR", "Out","SP", "PI", "VI","T","PW","EiP","OB","PR","ELD","NA"))
print(p1)
#print(p1)
```

<!--```{r}
#DF_ws<-subset(DF, Treatment=="WS" & Participant_ID=="T007" & Day=="Day2")
DF_ws<-subset(DF, Treatment=="WS")
# write.csv(DF_ws,'T007_Day2.csv')
p1<-ggplot(DF_ws) + 
  geom_histogram(aes(x=Ontology_One),stat="count", width=.5)+
  geom_histogram(aes(x=Ontology_Two),stat="count", width=.5)+
  geom_histogram(aes(x=Ontology_Three),stat="count", width=.5)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1))+
  ylab("Time [s]")+
  xlab("")+
  scale_y_continuous(breaks=seq(0,115000, 5000), limits=c(0,115000))+
  labs(title ="Single Ontologies For all Subjects" )+
  theme_gray()+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_x_discrete(limits=c( "CR","CW", "Out","ELD","EiP","SP", "PI","PR", "VI","PW","T","OB"))
  
print(p1)
```-->

```{r, echo=FALSE}
## Heatmap with percwntage for single subject

X<-c("CR", "CW", "EiP", "SP", "PR", "ELD", "PI", "VI","Out")
DF_Sub_Day<-subset(DF, Participant_ID=="T001" & Day=="Day4" & Treatment=="WS")
#write.csv(DF_Sub_Day,'T009_Day2.csv')
DF_Sub_Day$Onto_sep<-DF_Sub_Day$Activities_QC1

DF_Sub_Day<-DF_Sub_Day %>% separate(Onto_sep, c("A", "B"))


  for (i in 1:nrow(DF_Sub_Day)){
    
    if(is.na(DF_Sub_Day$B[i])){
      DF_Sub_Day$B[i]<-DF_Sub_Day$A[i]
    }
    
  }

#write.csv(DF_Sub_Day, 'ontology.csv')

mytable<-as.data.frame(table(DF_Sub_Day$A, DF_Sub_Day$B))
colnames(mytable)<-c("A", "B", "Time")
mytable<-subset(mytable, Time>0)

mytable$A<-as.character(mytable$A)
mytable$B<-as.character(mytable$B)
mytable<-mytable[!(mytable$A=="NA" | mytable$A=="Working" | mytable$A=="T" | mytable$A=="PW"),]

mytable_Sym <- data.frame(A = c(mytable[,"A"], mytable[,"B"]),
                          B = c(mytable[,"B"], mytable[,"A"]),
                          Time = c(mytable[,"Time"], mytable[,"Time"]))
mytable_Sym$A<-as.factor(mytable_Sym$A)
mytable_Sym$B<-as.factor(mytable_Sym$B)


rest_of_ontologies<-data.frame(A=setdiff(levels(factor(X)),levels(factor(mytable_Sym$A))),
                       B=setdiff(levels(factor(X)),levels(factor(mytable_Sym$A))),
                       Time=0)

mytable_Sym<-rbind(mytable_Sym, rest_of_ontologies)
mytable_Sym<-mytable_Sym[!(mytable_Sym$A=="OB"),]
#mytable_Sym <- melt(mytable_Sym,na.rm = TRUE)
#mytable_mat<-as.matrix(sapply(mytable, as.numeric))
#mytable_mat<-spread(mytable, B, Time,fill = NA, drop = FALSE)

mytable_mat<-acast(mytable_Sym, A~B, value.var='Time', fun.aggregate=mean)
        mytable_mat <- mytable_mat[, order(colnames(mytable_mat))]
        mytable_mat <- mytable_mat[order(rownames(mytable_mat)),]

# row.names(mytable_mat)<-mytable_mat$A
# mytable_mat$A<-NULL
#mytable_mat[lower.tri(mytable_mat)] <- NA
#main_mat<-main_mat+ mytable_mat

mytable_mat[lower.tri(mytable_mat)] <- NA
mytable_mat[is.nan(mytable_mat)] <- 0

mat <- melt(mytable_mat,na.rm = TRUE)
  #mat$value<-(mat$value)/1000
  mat$percent<-percent(mat$value/sum(mat$value))
  mat$percent_in_num<-(mat$value/sum(mat$value))*100
  mat$percent_in_num<-round(mat$percent_in_num, 2)
  mat$Var1 = as.factor(mat$Var1)
  mat$Var2 = as.factor(mat$Var2)
  mat = mat %>% mutate(value2 = ifelse(Var1==Var2, value, NA))
  mat = mat %>% mutate(value1 = ifelse(Var1==Var2, -1, value))
  mat$value1[is.na(mat$value1)] <- -2
  #print(mat)

  
    plot1 = ggplot(mat, aes(x=Var2, y=Var1))+
    geom_tile(aes(fill=percent_in_num))+
    geom_text(aes(label=percent_in_num, fontface=2), show.legend = FALSE,col="black",size=3, )+
    scale_fill_gradientn(colours = c("lightgray","dimgray"), name = "Time [s%]")+
    new_scale("fill") +
    geom_tile(aes(fill=percent_in_num), data = subset(mat, value1 > -1))+
    geom_text(aes(label=percent_in_num), show.legend = FALSE, col="black", size=2.5, data = subset(mat, value1 > 0))+
    scale_fill_gradientn(colours = c("white", "yellow", "red"), name = "")+
    new_scale("fill") +
    geom_tile(aes(fill=value1), data = subset(mat, value1 < -1 ), show.legend = FALSE)+
    scale_fill_gradientn(colours = c("white"))+
    xlab("")+
    ylab("")+
    labs(title=title)+
    theme(plot.title = element_text(hjust = 0.5),text = element_text(size=12,face="bold"),panel.background = element_blank(),panel.grid = element_blank()) +
    #labs(fill=" Time [s] in %")+
    scale_x_discrete(position = "top")+
    scale_y_discrete(limits = rev(levels(factor(X))))
    print(plot1)
```

```{r, echo=FALSE}

## Heatmap in percentage for multiple subjects.


X<-c("CR", "CW", "EiP", "T", "SP", "PR", "PW", "ELD", "PI", "VI","Out")
plot_list_heatmap<-list()
sid<-factor(DF$Participant_ID)
n=nlevels(sid)
for (i in 1:n) {
  DF_T001<-subset(DF, Participant_ID==levels(sid)[i] & DF$Treatment=="WS")
  D_id<-factor(DF_T001$Day)
  m=nlevels(D_id)
  for (j in 1:m) {
    DF_Sub_Day<-subset(DF_T001, Day==levels(D_id)[j])
    
    tab <- table(DF_Sub_Day$Activities_QC1)
    DF_Sub_Day<-DF_Sub_Day[DF_Sub_Day$Activities_QC1 %in% names(tab)[tab>60],]
    title=paste(levels(sid)[i],levels(D_id)[j])
    
    #if(title!="T005 Day4"){
    DF_Sub_Day$Onto_sep<-DF_Sub_Day$Activities_QC1
    DF_Sub_Day<-DF_Sub_Day %>% separate(Onto_sep, c("A", "B"))
    
    for (k in 1:nrow(DF_Sub_Day)){
      if(is.na(DF_Sub_Day$B[k])){
        DF_Sub_Day$B[k]<-DF_Sub_Day$A[k]
      }
    }
      mytable<-as.data.frame(table(DF_Sub_Day$A, DF_Sub_Day$B))
      colnames(mytable)<-c("A", "B", "Time")
      mytable<-subset(mytable, Time>0)
      
      mytable$A<-as.character(mytable$A)
      mytable$B<-as.character(mytable$B)
      mytable<-mytable[!(mytable$A=="NA" | mytable$A=="Working"),]
      
      mytable_Sym <- data.frame(A = c(mytable[,"A"], mytable[,"B"]),
                                B = c(mytable[,"B"], mytable[,"A"]),
                                Time = c(mytable[,"Time"], mytable[,"Time"]))
      mytable_Sym$A<-as.factor(mytable_Sym$A)
      mytable_Sym$B<-as.factor(mytable_Sym$B)
      
      
      rest_of_ontologies<-data.frame(A=setdiff(levels(factor(X)),levels(factor(mytable_Sym$A))),
                       B=setdiff(levels(factor(X)),levels(factor(mytable_Sym$A))),
                       Time=0) 

        mytable_Sym<-rbind(mytable_Sym, rest_of_ontologies)
        mytable_Sym<-mytable_Sym[!(mytable_Sym$A=="OB"),]
        mytable_mat<-acast(mytable_Sym, A~B, value.var='Time', fun.aggregate=mean)
        mytable_mat <- mytable_mat[, order(colnames(mytable_mat))]
        mytable_mat <- mytable_mat[order(rownames(mytable_mat)),]

        
        
        mytable_mat[lower.tri(mytable_mat)] <- NA
        mytable_mat[is.nan(mytable_mat)] <- 0
        mat <- melt(mytable_mat,na.rm = TRUE)
  # mat$value<-(mat$value)/1000
  # mat$value<-round(mat$value, 2)
        
  #Calculating percent
  mat$percent<-percent(mat$value/sum(mat$value))
  mat$percent<-percent(mat$value/sum(mat$value))
  mat$percent_in_num<-(mat$value/sum(mat$value))*100
  mat$percent_in_num<-round(mat$percent_in_num, 2)
  #Calculating percent
  
  mat$Var1 = as.factor(mat$Var1)
  mat$Var2 = as.factor(mat$Var2)
  mat = mat %>% mutate(value2 = ifelse(Var1==Var2, value, NA))
  mat = mat %>% mutate(value1 = ifelse(Var1==Var2, -1, value))
  mat$value1[is.na(mat$value1)] <- -2
  #print(mat)
  # mat$value1<-(mat$value1)/1000
  # mat$value2<-(mat$value2)/1000
  
  #mat$value<-round(mat$value, 1)

  if(str_detect(title, "T003")){
    # plot1 = ggplot(mat, aes(x=Var2, y=Var1))+
    # geom_tile(aes(fill=value2))+
    # scale_fill_gradientn(colours = c("lightgray","black"), name = "Time [s]*1000")+
    # new_scale("fill") +
    # geom_tile(aes(fill=value1), data = subset(mat, value1 > -1))+
    # scale_fill_gradientn(colours = c("yellow","white", "red"), name = "Time [s]*1000")+
    # new_scale("fill") +
    # geom_tile(aes(fill=value1), data = subset(mat, value1 < -1 ), show.legend = FALSE)+
    # scale_fill_gradientn(colours = c("white"))+
    # xlab("")+
    # ylab("")+
    # theme_bw()+
    # theme(text = element_text(size=15), panel.background = element_blank(), panel.grid = element_blank()) +
    # labs(fill="Time [s]*1000")+
    # scale_x_discrete(position = "top")+
    # scale_y_discrete(limits = rev(levels(factor(X))))+
    # labs(title = title)+
    # theme(plot.title = element_text(hjust = 0.5))
    # print(plot1)
    
    plot1 = ggplot(mat, aes(x=Var2, y=Var1))+
    #geom_tile(aes(fill=value2))+
    geom_tile(aes(fill=percent_in_num))+
    geom_text(aes(label=percent_in_num), show.legend = FALSE,col="black",size=2.5)+
    scale_fill_gradientn(colours = c("lightgray","dimgray"), name = "% Time [s]")+
    new_scale("fill") +
    geom_tile(aes(fill=percent_in_num), data = subset(mat, value1 > -1))+
    geom_text(aes(label=percent_in_num), show.legend = FALSE, col="black", size=2.5, data = subset(mat, value1 > 0))+
    #scale_fill_gradientn(colours = c("white", "yellow", "red"), name = "Time [s]*1000")+
    scale_fill_gradientn(colours = c("yellow","white", "red"), name = "% Time [s]")+
    new_scale("fill") +
    geom_tile(aes(fill=value1), data = subset(mat, value1 < -1 ), show.legend = FALSE)+
    scale_fill_gradientn(colours = c("white"))+
    xlab("")+
    ylab("")+
    labs(title=title)+
    theme(plot.title = element_text(hjust = 0.5),text = element_text(size=12, face = "bold"),panel.background = element_blank(),panel.grid = element_blank(), plot.margin = unit(c(0.5,.05,1.5,0.5), "cm")) +
    scale_x_discrete(position = "top")+
    scale_y_discrete(limits = rev(levels(factor(X))))
    print(plot1)
    plot_list_heatmap[[length(plot_list_heatmap) + 1]] <- plot1
  }
  else{
    plot1 = ggplot(mat, aes(x=Var2, y=Var1))+
    geom_tile(aes(fill=percent_in_num))+
    geom_text(aes(label=percent_in_num), show.legend = FALSE,col="black",size=2.5)+
    #scale_fill_gradientn(colours = c("lightgray","dimgray"), name = "Time [s]*1000")+
    scale_fill_gradientn(colours = c("lightgray","dimgray"), name = "Time [s] %")+
    new_scale("fill") +
    geom_tile(aes(fill=percent_in_num), data = subset(mat, value1 > -1))+
    geom_text(aes(label=percent_in_num), show.legend = FALSE, col="black", size=2.5, data = subset(mat, value1 > 0))+
    #scale_fill_gradientn(colours = c("white", "yellow", "red"), name = "Time [s]*1000")+
    scale_fill_gradientn(colours = c("white", "yellow", "red"), name = "Time [s] %")+
    new_scale("fill") +
    geom_tile(aes(fill=value1), data = subset(mat, value1 < -1 ), show.legend = FALSE)+
    scale_fill_gradientn(colours = c("white"))+
    xlab("")+
    ylab("")+
    labs(title=title)+
    theme(plot.title = element_text(hjust = 0.5),text = element_text(size=12, face = "bold"),panel.background = element_blank(),panel.grid = element_blank(), plot.margin = unit(c(0.5,.05,1.5,0.5), "cm")) +
    labs(fill=" X 1000")+
    scale_x_discrete(position = "top")+
    scale_y_discrete(limits = rev(levels(factor(X))))
    print(plot1)
    # plot1 = ggplot(mat, aes(x=Var2, y=Var1))+
    # geom_tile(aes(fill=value2))+
    # scale_fill_gradientn(colours = c("lightgray","black"), name = "Time [s]*1000")+
    # new_scale("fill") +
    # geom_tile(aes(fill=value1), data = subset(mat, value1 > -1))+
    # scale_fill_gradientn(colours = c("white","yellow", "red"), name = "Time [s]*1000")+
    # new_scale("fill") +
    # geom_tile(aes(fill=value1), data = subset(mat, value1 < -1 ), show.legend = FALSE)+
    # scale_fill_gradientn(colours = c("white"))+
    # xlab("")+
    # ylab("")+
    # theme_bw()+
    # theme(text = element_text(size=15),panel.background = element_blank(),panel.grid = element_blank()) +
    # labs(fill="Time [s]*1000")+
    # scale_x_discrete(position = "top")+
    # scale_y_discrete(limits = rev(levels(factor(X))))+
    # labs(title = title)+
    # theme(plot.title = element_text(hjust = 0.5))
    # print(plot1)
    plot_list_heatmap[[length(plot_list_heatmap) + 1]] <- plot1
  }
      
    }
  }
#ggarrange(plotlist = plot_list_heatmap, nrow = 2, ncol = 2, align = c("hv"))
```

```{r, echo=FALSE}
Draw_Timeline<-function(Data_Frame, Title, Color){
  
  timeline<-ggplot(Data_Frame,aes(x=Sinterface_Time, y=Day)) +
    
  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day1"),], aes(y=factor(1), colour=Ontology_One), shape=15)+
  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day1"),], aes(y=1.05, colour=Ontology_Two), shape=15)+
  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day1"),], aes(y=1.10, colour=Ontology_Three), shape=15)+
  
  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day2"),], aes(y=factor(2), colour=Ontology_One), shape=15)+
  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day2"),], aes(y=2.05, colour=Ontology_Two), shape=15)+
  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day2"),], aes(y=2.10, colour=Ontology_Three), shape=15)+

  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day3"),], aes(y=factor(3), colour=Ontology_One), shape=15)+
  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day3"),], aes(y=3.05, colour=Ontology_Two), shape=15)+
  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day3"),], aes(y=3.10, colour=Ontology_Three), shape=15)+
  
  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day4"),], aes(y=factor(4), color=Ontology_One), shape=15)+
  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day4"),], aes(y=4.05, color=Ontology_Two), shape=15)+
  geom_point(data = Data_Frame[which(Data_Frame$Day=="Day4"),], aes(y=4.10, color=Ontology_Three), shape=15)+
  
  scale_y_discrete(breaks=c("1", "2", "3", "4"),labels=c("Day1", "Day2","Day3", "Day4"))+
  theme(text = element_text(face = "bold",size=12 ,color = "black"),plot.title = element_text(hjust = 0.5), panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank())+
  labs(title = Title , x="Time [s]", y="")+
  theme(legend.position = "right")+theme(legend.title = element_blank(), legend.text=element_text(size=10), legend.background = element_blank())+
  theme(plot.title = element_text(size=20))+
  scale_color_manual(values = Color, limits = c("CR", "PR", "CW", "PW", "PI", "VI", "Out", "SP", "Out", "ELD", "EiP", "T"))+
  guides(color = guide_legend(override.aes = list(size = 4)))+
  scale_x_continuous(breaks = seq(0,24000, by=2000))
  print(timeline)
}
```


```{r, echo=FALSE}
## Time-line for all subjects
Ontology_Color <- c( "CR" = "green4",  "PR" = "lightgreen", "CW" = "blue", "PW" = "cyan", "PI" = "black","VI" = "yellow","Out" = "white","SP" = "red","ELD" = "orange","EiP" = "magenta", "T" = "brown", "nil"="gray92")


plot_list_timeline<-list()
SubjectID<-factor(DF$Participant_ID)
numberSid=nlevels(SubjectID)
for (i in 1:numberSid) {
  DF_Sub<-subset(DF, Participant_ID==levels(SubjectID)[i] & DF$Treatment=="WS")
      subject_title=levels(SubjectID)[i]
      tab <- table(DF_Sub$Activities_QC1)
      DF_Sub<-DF_Sub[DF_Sub$Activities_QC1 %in% names(tab)[tab>60],]
      DF_Sub$Ontology_Two[DF_Sub$Ontology_Two==""]<-"nil"
      DF_Sub$Ontology_Three[DF_Sub$Ontology_Three==""]<-"nil"
      
      plot_list_timeline[[length(plot_list_timeline) + 1]]<- Draw_Timeline(DF_Sub, subject_title, Ontology_Color)
}
#ggarrange(plotlist = plot_list_timeline, nrow = 1, ncol = 1, align = c("hv"))
```


```{r, echo=FALSE}

##Timeline for a single subject

pal <- c( "CR" = "green",  "PR" = "lightgreen", "CW" = "blue", "PW" = "cyan", "PI" = "lightskyblue","VI" = "yellow","Out" = "white","SP" = "red","ELD" = "orange","EiP" = "magenta", "T" = "brown", "nil"="gray92")

DF_Sub<-subset(DF, Participant_ID=="T005" &Treatment=="WS")
#write.csv(DF_Sub, 'T009_Day2.csv')
      tab <- table(DF_Sub$Activities_QC1)
      DF_Sub<-DF_Sub[DF_Sub$Activities_QC1 %in% names(tab)[tab>60],]
      
      DF_Sub$B[DF_Sub$B==""]<-"nil"
      DF_Sub$C[DF_Sub$C==""]<-"nil"
      
timeline<-ggplot(DF_Sub,aes(x=Sinterface_Time, y=Day)) +
  geom_point(data = DF_Sub[which(DF_Sub$Day=="Day1"),], aes(y=factor(1), colour=A), shape=15)+
  geom_point(data = DF_Sub[which(DF_Sub$Day=="Day1"),], aes(y=1.05, colour=B), shape=15)+
  geom_point(data = DF_Sub[which(DF_Sub$Day=="Day1"),], aes(y=1.10, colour=C), shape=15)+
  scale_y_discrete(breaks=c("1", "2", "3", "4"),labels=c("Day1", "Day2","Day3", "Day4"))+
  
  #theme_classic()+
  theme(text = element_text(face = "bold",size=12 ,color = "black"),plot.title = element_text(hjust = 0.5), panel.border = element_blank(),     panel.grid.major = element_blank(),panel.grid.minor = element_blank())+
  labs(title = "T005", x="", y="")+
  theme(legend.position = "right")+theme(legend.title = element_blank(), legend.text=element_text(size=10), legend.background = element_blank())+
  theme(plot.title = element_text(size=20))+
  scale_color_manual(values = pal, limits = c("CR", "PR", "CW", "PW", "PI", "VI", "Out", "SP", "Out", "ELD", "EiP", "T"))+
  guides(color = guide_legend(override.aes = list(size = 4)))+
  scale_x_continuous(breaks = seq(0,24000, by=2000))

print(timeline)
```



>>>>>>> local-shaila-new
