---
title: "Supplementary Plots - Raw, Smooth, Log Transformed"
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering}
output:
  pdf_document: default
  html_document: default
geometry: top=3.5cm, bottom=3cm
---




```{r echo = FALSE, warning = FALSE, message = FALSE, results='hide'} 
#-------------------------#
#--------LIBRARIES--------#
#-------------------------#
library(scales)
library(ggplot2)
library(dplyr) # Some problem occured for loading the dplyr package at the beginning


#-------------------------#
#-----GLOBAL VARIABLES----#
#-------------------------#
## CHANGE this path if needed
source(file.path(getwd(), 'us-common-functions.R'))
project_dir <- dirname(getwd())
setwd(project_dir)


``` 

\newpage
```{r echo=FALSE, warning = FALSE, message = FALSE}
#-------------------------#
#-----   FUNCTIONS    ----#
#-------------------------#
save_plot <- function(plot_name, plot, width=default_plot_width, height=default_plot_height) {
  ggsave(paste0(plot_name, '.pdf'), plot, width=width, height=height)
  ggsave(paste0(plot_name, '.pdf'), plot, device=cairo_pdf, width=width, height=height)
}

read_data <- function() {
  full_df <<- custom_read_csv(file.path(project_dir, curated_data_dir, physiological_data_dir, full_df_file_name))
  # print_msg(colnames(full_df))
}

get_signal_data <- function(day_df, signal) {
  # if (signal=='PP') {
  #   signal_df <- full_df %>% 
  #     select(Participant_ID, Day, Treatment, TreatmentTime, Raw_PP, PP, Trans_PP)
  # } else if (signal=='E4_EDA') {
  #   signal_df <- full_df %>% 
  #     select(Participant_ID, Day, Treatment, TreatmentTime, Raw_E4_EDA, E4_EDA, Trans_E4_EDA)
  # } else if (signal=='E4_HR') {
  #   signal_df <- full_df %>% 
  #     select(Participant_ID, Day, Treatment, TreatmentTime, Raw_E4_HR, Trans_E4_HR)
  # } else if (signal=='iWatch_HR') {
  #   signal_df <- full_df %>% 
  #     select(Participant_ID, Day, Treatment, TreatmentTime, Raw_iWatch_HR, Trans_iWatch_HR)
  # }
  
  signal_df <- day_df %>% 
      select(Participant_ID, 
             Day, 
             Treatment, 
             TreatmentTime, 
             Mask,
             !!paste0('Raw_', signal), 
             !!signal, 
             !!paste0('Trans_', signal))

  signal_df
}

 get_themed_plot <- function(plot) {
  plot <- plot +
    theme_bw() +
    theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        text=element_text(size=18),
        axis.text = element_text(size=16),
        plot.title = element_text(hjust=0.5, size=22)
        )
  plot
}

get_ticks_no <- function(treatment) {
  if (treatment=='RB') {
    return(25)
  }
  
  return(40)
}

draw_signal_plots <- function(test=F) {
  if (test==TRUE) {
    
    # subj_list <- c('T003')
    # day_list <- c('Day1')
    
    subj_list <- c('T003', 'T005')
    day_list <- unique(full_df$Day)
    
  } else {
    subj_list <- unique(full_df$Participant_ID)
    # subj_list <- subj_list[-length(subj_list)]
    day_list <- unique(full_df$Day)
  }
  
  for (subj in subj_list) {
    subj_df <- full_df %>% filter(Participant_ID==subj)
    
    for (day in day_list) {
      day_df <- subj_df %>% filter(Day==day) 
      
      for (signal in signal_list) {
        signal_df <- get_signal_data(day_df, signal)
        
        for (treatment in unique(day_df$Treatment)) {
          treatment_df <- day_df %>% 
            filter(Treatment==treatment) 
          
          if (signal=='iWatch_HR') {
            treatment_df <- treatment_df %>%
              na.omit()
          }
          
          message(paste(subj, day, signal, treatment))
          
          if (nrow(treatment_df)>0) {
            plot <- ggplot(data=treatment_df, aes(x=TreatmentTime)) + 
              geom_line(aes_string(y=paste0('Raw_', signal)),
                        color='gray',
                        alpha = 0.6)  
          
          if(signal %in% colnames(treatment_df)) {
            plot <- plot +
                geom_line(aes_string(y=signal),
                        color='blue',
                        alpha = 0.8) 
            }
            
            plot <- plot +
              ggtitle(paste0(subj, ' - ', day, ' - ', treatment)) +
              scale_x_continuous(breaks = scales::pretty_breaks(n = get_ticks_no(treatment))) +
              scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
              # scale_x_continuous(breaks = round(seq(min(treatment_df$TreatmentTime), 
              #                                       max(treatment_df$TreatmentTime), 
              #                                       by = 500), 1)) +
              xlab('Time [s]') +
              ylab(signal) 
            plot <- get_themed_plot(plot)
            print(plot)

            save_plot(file.path(project_dir, plots_dir, 'raw-smooth-signals',
                            paste0(subj, '_', day, '_', treatment, '_', signal)), 
                  plot,
                  24,
                  8
                  )
            
            plot <- ggplot(data=treatment_df, aes(x=TreatmentTime)) +
              geom_line(aes_string(y=paste0('Trans_', signal)),
                        color='green',
                        alpha = 0.8) +
              xlab('Time [s]') +
              ylab(paste0('ln( ', signal, ' )'))
            print(get_themed_plot(plot))
          }
        }
      }
    }
  }
}
```




<!-- \newpage -->
```{r echo=FALSE, warning = FALSE, message = FALSE}
read_data()
```



\newpage
<!-- Plots -->
------------------------------
```{r echo=FALSE, warning = FALSE, message = FALSE}
# signal_list <<- c('PP', 'E4_EDA', 'E4_HR', 'iWatch_HR')
signal_list <<- c('PP')

draw_signal_plots(test=TRUE)
# draw_signal_plots()
```

