---
title: "Supplementary Plots"
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering}
output:
  pdf_document: default
  html_document: default
geometry: top=3.5cm, bottom=3cm
---




```{r echo = FALSE, warning = FALSE, message = FALSE, results='hide'} 
#-------------------------#
#--------LIBRARIES--------#
#-------------------------#
library(ggplot2)
library(dplyr) # Some problem occured for loading the dplyr package at the beginning




#-------------------------#
#-----GLOBAL VARIABLES----#
#-------------------------#
## CHANGE this path if needed
source(file.path(getwd(), 'us-common-functions.R'))
project_dir <- dirname(getwd())
setwd(project_dir)


# full_df <<- tibble()

``` 

\newpage
```{r echo=FALSE, warning = FALSE, message = FALSE}
#-------------------------#
#-----   FUNCTIONS    ----#
#-------------------------#
# merge_data <- function() {
#   physiological_data_path <- file.path(project_dir, curated_data_dir, physiological_data_dir)
#   
#   qc0_df <- custom_read_csv(file.path(physiological_data_path, qc0_final_file_name)) %>% 
#     select(Timestamp, Raw_PP, Raw_E4_EDA, Raw_E4_HR, Raw_iWatch_HR)
#     
#   ############################################################################################
#   #                             This might be QC1 or QC2
#   ############################################################################################
#   qc_df <- custom_read_csv(file.path(physiological_data_path, qc1_file_name)) %>% 
#     select(Timestamp, PP, E4_HR, E4_EDA, iWatch_HR, Mask) 
#     # select(Participant_ID, Day, Treatment, Timestamp, TreatmentTime, PP, E4_HR, E4_EDA, iWatch_HR, Mask) 
#   # %>% 
#   #   dplyr::rename(
#   #     Raw_E4_HR=E4_HR,
#   #     Raw_iWatch_HR=iWatch_HR
#   #   )
#     
#   transformed_df <- custom_read_csv(file.path(physiological_data_path, qc1_transformed_file_name)) %>% 
#     select(Participant_ID, Day, Treatment, TreatmentTime, Timestamp, PP, E4_HR, E4_EDA, iWatch_HR) %>% 
#     dplyr::rename(
#       Trans_PP=PP,
#       Trans_E4_HR=E4_HR,
#       Trans_E4_EDA=E4_EDA,
#       Trans_iWatch_HR=iWatch_HR
#     )
#   ############################################################################################
#     
#   
#   
#   # print_msg(head(qc0_df, 2))
#   # print_msg(head(qc_df, 2))
#   # print_msg(head(transformed_df, 2))
#   
#   
#   print_msg('Merging data...')
#   
#   full_df <- transformed_df %>%
#   #   # merge(qc0_df, by=c('Participant_ID', 'Day', 'Treatment', 'TreatmentTime'), all=T) %>%
#   #   # merge(qc_df, by=c('Participant_ID', 'Day', 'Treatment', 'TreatmentTime'), all=T) %>%
# 
#     # merge(qc0_df, by='Timestamp', all=T) %>%
#     # merge(qc_df, by='Timestamp', all=T) %>%
# 
#     dplyr::full_join(qc0_df, by='Timestamp') %>%
#     dplyr::full_join(qc_df, by='Timestamp') %>%
# 
#     
#     arrange(Participant_ID, Day, Treatment, TreatmentTime) %>% 
#     select(
#       Participant_ID,
#       Day,
#       Treatment,
#       Timestamp,
#       TreatmentTime,
# 
#       Raw_PP,
#       PP,
#       Trans_PP,
# 
#       Raw_E4_EDA,
#       E4_EDA,
#       Trans_E4_EDA,
# 
#       Raw_E4_HR,
#       E4_HR,
#       Trans_E4_HR,
# 
#       Raw_iWatch_HR,
#       iWatch_HR,
#       Trans_iWatch_HR,
# 
#       Mask
#     )
#   
#   print_msg('Done merging data...')
#   # print_msg(colnames(full_df))
#   convert_to_csv(full_df, file.path(physiological_data_path, full_df_file_name))
# }

read_data <- function() {
  full_df <<- custom_read_csv(file.path(project_dir, curated_data_dir, physiological_data_dir, full_df_file_name))
  # print_msg(colnames(full_df))
}


# Participant_ID, Day, Treatment, TreatmentTime,  
# Raw_PP, PP, Trans_PP,  
# Raw_E4_EDA, E4_EDA, Trans_E4_EDA,  
# E4_HR, Trans_E4_HR,  
# iWatch_HR, Trans_iWatch_HR,  Mask
get_signal_data <- function(signal) {
  # if (signal=='PP') {
  #   signal_df <- full_df %>% 
  #     select(Participant_ID, Day, Treatment, TreatmentTime, Raw_PP, PP, Trans_PP)
  # } else if (signal=='E4_EDA') {
  #   signal_df <- full_df %>% 
  #     select(Participant_ID, Day, Treatment, TreatmentTime, Raw_E4_EDA, E4_EDA, Trans_E4_EDA)
  # } else if (signal=='E4_HR') {
  #   signal_df <- full_df %>% 
  #     select(Participant_ID, Day, Treatment, TreatmentTime, Raw_E4_HR, Trans_E4_HR)
  # } else if (signal=='iWatch_HR') {
  #   signal_df <- full_df %>% 
  #     select(Participant_ID, Day, Treatment, TreatmentTime, Raw_iWatch_HR, Trans_iWatch_HR)
  # }
  
  signal_df <- full_df %>% 
      select(Participant_ID, 
             Day, 
             Treatment, 
             TreatmentTime, 
             !!paste0('Raw_', signal), 
             !!signal, 
             !!paste0('Trans_', signal))

  signal_df
}


draw_signal_plots <- function(signal_df, signal, test) {
  if (test==TRUE) {
    subj_list <- c('T003')
    day_list <- c('Day1')
    
  } else {
    subj_list <- unique(signal_df$Participant_ID)
    subj_list <- subj_list[-length(subj_list)]
    day_list <- unique(signal_df$Day)
  }
  
  for (subj in subj_list) {
    subj_df <- signal_df %>% filter(Participant_ID==subj)
    
    for (day in day_list) {
      day_df <- subj_df %>% filter(Day==day) 
      
      for (treatment in unique(day_df$Treatment)) {
        treatment_df <- day_df %>% filter(Treatment==treatment) %>% 
          na.omit()
        
        message(paste(subj, day, treatment))
        
        plot <- ggplot(data=treatment_df, aes(x=TreatmentTime)) + 
            geom_line(aes_string(y=paste0('Raw_', signal)),
                      color='gray',
                      alpha = 0.6)  
        
        if(signal %in% colnames(treatment_df)) {
          plot <- plot +
            geom_line(aes_string(y=signal),
                    color='blue',
                    alpha = 0.8) 
        }
        
        plot <- plot +
          # geom_line(aes_string(y=signal),
          #           color='blue',
          #           alpha = 0.8) +
          
          ggtitle(paste0(subj, ' - ', day, ' - ', treatment)) +
          xlab('Time [s]') +
          ylab(signal) 
          
          
          # geom_line(aes_string(y=paste0('Trans_', signal)),
          #           color='green',
          #           alpha = 0.8) +
          # 
          # scale_y_continuous(
          #   limits=c(0, 1),
          #   name = signal,
          #   sec.axis = sec_axis(
          #     trans=~.*1,
          #     # trans='log',
          #     name=paste0('ln(', signal, ')'))
          # ) +
          

        plot <- plot +  
          theme_bw() +
          theme(
                panel.grid.major = element_blank(),
                panel.grid.minor = element_blank(),
                axis.line = element_line(colour = "black"),
                plot.title = element_text(hjust = 0.5, size = 16)
                )
        
        print(plot)
        
        
        plot <- ggplot(data=treatment_df, aes(x=TreatmentTime)) +
          geom_line(aes_string(y=paste0('Trans_', signal)),
                    color='green',
                    alpha = 0.8) +
          xlab('Time [s]') +
          ylab(paste0('ln( ', signal, ' )')) +
          theme_bw() +
          theme(
                panel.grid.major = element_blank(),
                panel.grid.minor = element_blank(),
                axis.line = element_line(colour = "black"),
                plot.title = element_text(hjust = 0.5, size = 16)
                )

        print(plot)
      }
    }
  }
}

draw_plots <- function(test=FALSE) {
  signal_list <- c('PP', 'E4_EDA', 'E4_HR', 'iWatch_HR')
  # signal_list <- c('PP')

  for (signal in signal_list) {
    signal_df <- get_signal_data(signal)
    draw_signal_plots(signal_df, signal, test)
  }
}
```




<!-- \newpage -->
```{r echo=FALSE, warning = FALSE, message = FALSE}
# merge_data()
read_data()
```



\newpage
<!-- Plots -->
------------------------------
```{r echo=FALSE, warning = FALSE, message = FALSE}
# draw_plots(test=TRUE)
draw_plots()
```

