---
title: "Segmented_data"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(ggpubr)
library(DataCombine)
library(dplyr)
library(reshape2)
library(tidyr)
library(stringr)
library(plyr)
library(ggplot2)
library(dplyr)
library(miceadds)
library(gtools)
library(ggpubr)
library(gvlma)
library(MASS)
library(reshape2)
library(zoo)
```


```{r, echo=FALSE}
# current_dir <- getwd()
# setwd('..')
# root_dir <- getwd()
# data_dir <- file.path(root_dir, 'curated-data/physiological-data')
# plot_dir <- file.path(root_dir,'plots/CaseStudy')
# data_file_name<-'full_df.csv'
# # data_file_name<-'Full_Df_Segment.csv'
# curated_data_dir <- file.path(root_dir, 'curated-data/physiological-data')
# Data1<-read.csv(file.path(data_dir,data_file_name),stringsAsFactors = FALSE)
# 
# 
# count(factor(Data1$Segments_Activity))
```

```{r, echo=FALSE}
  # Data1$Segments_Activity<-NULL
  # Data1 <- Data1 %>% 
  #   mutate(Segments_Activity = case_when(
  #     str_detect(Reduced_Activities_QC1, Activity_pattern)~'RW',
  #     str_detect(Reduced_Activities_QC1, Out_pattern)~'Out', Treatment=='WS'~'Other'))
  # 
  # Data1 <- Data1 %>%
  #   mutate(Segments_Activity = replace(Segments_Activity, is.na(Reduced_Activities_QC1), NA))

```


```{r, echo=FALSE}

# segment_df <- Data1 %>%
#     # dplyr::select(Participant_ID, Day, Treatment,
#     #               Timestamp, Sinterface_Time, TreatmentTime,
#     #               Trans_PP,
#     #               Segments_Activity,
#     #               Mask) %>%
#     dplyr::mutate(Segments_Activity=case_when(Treatment=="RB"~"Out",
#                                             TRUE~.$Segments_Activity)) %>%
#     dplyr::group_by(Participant_ID, Day) %>%
#     dplyr::mutate(Counter=sequence(rle(as.character(Segments_Activity))$lengths),
#            Segment=case_when(Segments_Activity=="Out" & Counter==1~1, TRUE~0),
#            Segment=ifelse(Segment==1, cumsum(Segment==1), NA),
#            Segment=na.locf0(Segment)) %>%
#     dplyr::select(-Counter)
# 
#   # View(segment_df)
# levels(factor(segment_df$Segment))
# count(factor(segment_df$Segments_Activity))
```



```{r, echo=FALSE}
  # segment_meta_data_df_1 <- segment_df %>%
  #   dplyr::group_by(Participant_ID, Day) %>%
  #   dplyr::summarize(Length_Day=n(),
  #             Mean_PP_RestingBaseline=mean(Trans_PP[Segments_Activity=="Out" & Segment==1], na.rm = TRUE),
  #             Length_RestingBaseline=length(Trans_PP[Segments_Activity=="Out" & Segment==1])) %>%
  #   ungroup()
  #   
  # segment_meta_data_df <- segment_df %>%
  #   dplyr::group_by(Participant_ID, Day, Segment) %>%
  #   dplyr::summarize(
  #         StartTime=head(Timestamp, 1),
  #         EndTime=tail(Timestamp, 1),
  #         Length_Segment=n(),
  #         Length_Break=sum(Segments_Activity=="Out", na.rm = TRUE),
  #         Length_Reading_Writing=sum(Segments_Activity=="RW", na.rm = TRUE),
  #         Mean_PP_Reading_Writing=mean(Trans_PP[Segments_Activity=="RW"], na.rm = TRUE),
  #         Length_Other_Activities=sum(Segments_Activity=="Other", na.rm = TRUE),
  #         Mean_PP_Other_Activities=mean(Trans_PP[Segments_Activity=="Other"], na.rm = TRUE)) %>% 
  #   merge(segment_meta_data_df_1, by=c("Participant_ID", "Day")) %>%
  #   dplyr::select(
  #     Participant_ID,
  #     Day,
  #     StartTime,
  #     EndTime,
  #     Length_Day,
  #     Segment,
  #     Length_Segment,
  #     Length_RestingBaseline,
  #     Mean_PP_RestingBaseline,
  #     Length_Break,
  #     Length_Reading_Writing,
  #     Mean_PP_Reading_Writing,
  #     Length_Other_Activities,
  #     Mean_PP_Other_Activities
  #   )
  # 
  # View(segment_meta_data_df)
```




```{r, echo=FALSE}

# segment_meta_data_df_filtered <- segment_meta_data_df %>% filter(Length_Break < 30)
# 
# 
# count(segment_df$Reduced_Activities_QC1)
# count(segment_df$Segments_Activity)
# 
# for (i in 1:nrow(segment_meta_data_df_filtered)) {
#   segment_df <- segment_df %>%
#     dplyr::mutate(
#       Reduced_Activities_QC1 = case_when(
#         Participant_ID == segment_meta_data_df_filtered$Participant_ID[i] &
#           Day == segment_meta_data_df_filtered$Day[i] &
#           Reduced_Activities_QC1 == "Out" &
#           Segment == segment_meta_data_df_filtered$Segment[i] ~ "NA",
#         TRUE ~ Reduced_Activities_QC1
#       ),
#       Segments_Activity = case_when(
#         Participant_ID == segment_meta_data_df_filtered$Participant_ID[i] &
#           Day == segment_meta_data_df_filtered$Day[i] &
#           Segments_Activity == "Out" &
#           Segment == segment_meta_data_df_filtered$Segment[i] ~ "NA",
#         TRUE ~ Segments_Activity
#       )
#     )
# }
# 
# 
# 
# segment_df <- segment_df %>%
#     dplyr::mutate_at(vars(Reduced_Activities_QC1),na_if,"NA") %>% 
#     dplyr::mutate_at(vars(Segments_Activity),na_if,"NA")
# 
# segment_df <- segment_df %>%
#     mutate(Reduced_Activity_One = replace(Reduced_Activity_One, is.na(Reduced_Activities_QC1), NA)) %>% 
#     mutate(Reduced_Activity_Two = replace(Reduced_Activity_Two, is.na(Reduced_Activities_QC1), NA)) %>% 
#     mutate(Reduced_Activity_Three = replace(Reduced_Activity_Three, is.na(Reduced_Activities_QC1), NA))
# 
# count(segment_df$Reduced_Activities_QC1)
# count(segment_df$Segments_Activity)
# 
# 
# 
# segment_df <- segment_df %>% filter(!is.na(Segments_Activity))
# 
# file_name='Full_Df_Segment.csv'
# write.csv(segment_df,file.path(curated_data_dir, file_name), row.names = FALSE)

```

```{r, echo=FALSE}
current_dir <- getwd()
setwd('..')
root_dir <- getwd()
data_dir <- file.path(root_dir, 'curated-data/physiological-data')
plot_dir <- file.path(root_dir,'plots/CaseStudy')
data_file_name<-'segment_meta_data_df.csv'
curated_data_dir <- file.path(root_dir, 'curated-data/physiological-data')
Data<-read.csv(file.path(data_dir,data_file_name),stringsAsFactors = FALSE)

questionnaire_data_file <- 'Questionnaire Data.csv'
Q_Data <- read.csv(file.path(data_dir,questionnaire_data_file),stringsAsFactors = FALSE)
Q_Data <- Q_Data[,-c(1, 3:34 )]
```


```{r, echo=FALSE}
Q_Data$Gender = c("Male", "Female", "Male", "Female", "Male", "Female", "Female", "Male", "Male")
```

```{r, echo=FALSE, warning=FALSE}
Data$Segment <- paste0("Seg-",Data$Segment)
Data$Normalized_PP_mean_RW = Data$Mean_PP_Reading_Writing - Data$Mean_PP_RestingBaseline
Data$Normalized_PP_mean_Other = Data$Mean_PP_Other_Activities - Data$Mean_PP_RestingBaseline


Merged_Data <- merge(x = Data, y = Q_Data, by = "Participant_ID")
Merged_Data = Merged_Data %>% arrange(Participant_ID, Day, Segment)

Merged_Data = Merged_Data[with (Merged_Data, order(Participant_ID, Day, Segment)), ]


Segmented_Data = Merged_Data[,c(
  'Participant_ID',
  'Gender',
  'Trait_anxiety',
  'Personality_AB',
  'BFI_.Agreeableness',
  'BFI_.Conscientiousness',
  'BFI_.Extraversion',
  'BFI_.Neuroticism',
  'BFI_.Openness',
  'StartDay_S.Anxiety.Before.Deadline',
  'EndDay_S.Anxiety.Before.Deadline',
  'StartDay_S.Anxiety.After.Deadline',
  'EndDay_S.Anxiety.After.Deadline',
  'Day',
  'Length_Day',
  'Segment',
  'Length_Segment',
  'Length_RestingBaseline',
  'Mean_PP_RestingBaseline',
  'Length_Break',
  'Length_Reading_Writing',
  'Mean_PP_Reading_Writing',
  'Length_Other_Activities',
  'Mean_PP_Other_Activities'
)]


file_name='Meta_data_with_psychometric.csv'
write.csv(Segmented_Data,file.path(curated_data_dir, file_name), row.names = FALSE)

Data_to_plot <- melt(Merged_Data[, c(
  'Participant_ID',
  'Day',
  'Segment',
  'Length_Break',
  'Length_Reading_Writing',
  'Length_Other_Activities'
)])

```


```{r, echo=FALSE, warning=FALSE}
# yaxis_title = expression(Delta~"ln("~bar("PP")~paste('[',''^'o','C',''^2,'])'))
# yaxis_title = bquote(paste(' ln(PP) [ ', '' ^ 'o', 'C', '' ^ 2, ' ]'))

participant_No = factor(Data_to_plot$Participant_ID)
participant_number = nlevels(participant_No)
for (i in 1:participant_number) {
  Participant_day <-
    subset(Data_to_plot, Participant_ID == levels(participant_No)[i])
  Day_No <- factor(Participant_day$Day)
  numberOfDay = nlevels(Day_No)
  for (j in 1:numberOfDay) {
    Segments_Day <- subset(Participant_day, Day == levels(Day_No)[j])
    # Segments_Day<- reorder(Segments_Day$variable)
    
    title = paste(levels(participant_No)[i], levels(Day_No)[j])
    
    plot <-
      ggplot(Segments_Day, aes(fill = variable, y = value, x = Segment)) +
      geom_bar(position = "stack", stat = "identity") +
      theme_minimal() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        # plot.title = element_text(hjust = -0.05, vjust=2.12,size = 20, face = "bold", margin=margin(10,0,5,0)),
        legend.title = element_blank(),
        legend.position = 'bottom',
        axis.text.x = element_text(face = "bold", size = 10),
        axis.text.y = element_text(face = "bold", size = 10),
        axis.title.x = element_text(face = "bold", size = 10),
        axis.title.y = element_text(face = "bold", size = 10),
        plot.title = element_text(hjust = 0.5)
      ) + xlab("Segments") + ylab("Time [s]") + ggtitle(title)
    
    print(plot)
    
    # Segments_Day <- subset(Data, Day == levels(Day_No)[j])
    # 
    # plot_pp_line <- ggplot(data = Segments_Day) +
    #   geom_hline(
    #     aes(yintercept = Normalized_PP_mean_RW, colour = Segment),
    #     size = 1.5,
    #     linetype = "dashed"
    #   ) +
    #   theme_minimal() +
    #   theme(
    #     panel.grid.major = element_blank(),
    #     panel.grid.minor = element_blank(),
    #     legend.title = element_blank(),
    #     legend.position = 'bottom',
    #     axis.text.y = element_text(face = "bold", size = 10),
    #     axis.title.y = element_text(face = "bold", size = 10)
    #   ) + ylab(yaxis_title)
    # print(plot_pp_line)
    
    # plot_segment = ggarrange(plot, plot_pp_line, nrow = 2, ncol = 1)
    # plot_name=paste0(levels(Day_No)[j],".pdf")
    #
    #
    # full_path<-file.path(plot_dir,plot_name,sep="")
    # ggsave(full_path, plot_segment, width = 8.5, height = 11, units = "in")
    
  }
  
}

```



```{r, echo=FALSE, warning=FALSE}
# yaxis_title = bquote(paste('ln(PP) [ ',''^'o','C',''^2,' ]'))
yaxis_title = expression(Delta~"ln("~bar("PP")~paste('[',''^'o','C',''^2,'])'))
participant_No = factor(Merged_Data$Participant_ID)
participant_number = nlevels(participant_No)
for (i in 1:participant_number) {
  subject <- subset(Merged_Data, Participant_ID == levels(participant_No)[i])
  min_y = min(subject$Normalized_PP_mean_RW)
  max_y = max(subject$Normalized_PP_mean_RW)
  
  plot <- ggplot(subject, aes(fill = Segment, y = Normalized_PP_mean_RW, x = Day)) +
    geom_bar(position = "dodge", stat = "identity") +
    theme_minimal() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.title = element_blank(),
      legend.position = 'bottom',
      axis.text.x = element_text(face = "bold", size = 10),
      plot.title = element_text(hjust = 0.5)
    ) + ylim(min_y, max_y) + ggtitle(levels(participant_No)[i]) + ylab(yaxis_title)
  print(plot)
}  
```

\newpage
## Model1 with Normalized_mean_RW ~ Length_Break + Length_Reading_Writing + Length_Other_Activities
```{r, echo=FALSE}
model1 = lm(Normalized_PP_mean_RW ~ Length_Break + Length_Reading_Writing + Length_Other_Activities + Gender, data = Merged_Data)
summary(model1)
anova(model1)
```

\newpage
## Model2 with Normalized_mean_RW ~ Length_Break + Length_Reading_Writing + Length_Other_Activities + Trait_anxiety
```{r, echo=FALSE}
model2 = lm(Normalized_PP_mean_RW ~ Length_Break + Length_Reading_Writing + Length_Other_Activities + Trait_anxiety, data = Merged_Data)
summary(model2)
anova(model2)
```


\newpage
## Model3 with Normalized_mean_RW ~ Length_Break + Length_Reading_Writing + Length_Other_Activities + Normalized_mean_Other
```{r, echo=FALSE}
# Merged_Data$Gender <- relevel(Merged_Data$Gender, ref = "Male")
model3 = lm(Normalized_PP_mean_RW ~ Length_Break + Length_Reading_Writing + Length_Other_Activities + Normalized_PP_mean_Other, data = Merged_Data)
summary(model3)
anova(model3)
```