---
title: 'Signal and Activity Comparison Plots'
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering}
output:
  pdf_document: default
  html_document: default
geometry: top=3.5cm, bottom=3cm
---




```{r echo = FALSE, warning = FALSE, message = FALSE, results='hide'} 
#-------------------------#
#--------LIBRARIES--------#
#-------------------------#
library(reshape2)
library(ggplot2)
library(dplyr) # Some problem occured for loading the dplyr package at the beginning
library(grid)
library(gridExtra)



#-------------------------#
#-----GLOBAL VARIABLES----#
#-------------------------#
## CHANGE this path if needed
source(file.path(getwd(), 'us-common-functions.R'))
project_dir <- dirname(getwd())
setwd(project_dir)


# signal_list <- c('PP', 'E4_EDA', 'E4_HR', 'iWatch_HR')
signal_list <- c('PP')


Ontology_Color <- c( "R" = "springgreen", 
                     "W" = "blue",  
                     "I" = "orange", 
                     "Out" = "gray92", 
                     "SP" = "red", 
                     "SA" = "magenta", 
                     "NA"="white"
                     )
``` 

\newpage
```{r echo=FALSE, warning = FALSE, message = FALSE}
#-------------------------#
#-----   FUNCTIONS    ----#
#-------------------------#
save_plot <- function(plot_name, plot, width=default_plot_width, height=default_plot_height) {
  ggsave(paste0(plot_name, '.pdf'), plot, width=width, height=height)
  ggsave(paste0(plot_name, '.pdf'), plot, device=cairo_pdf, width=width, height=height)
}


read_data <- function() {
  if (test==TRUE) {
    full_df <<- custom_read_csv(file.path(project_dir, curated_data_dir, physiological_data_dir, 'mini_full_df.csv'))
  } else {
    full_df <<- custom_read_csv(file.path(project_dir, curated_data_dir, physiological_data_dir, full_df_file_name))
  }
   
  # print_msg(colnames(full_df))
  # print_msg(unique(full_df$Reduced_Application_final))
}


add_theme <- function(plot) {
  plot <- plot + 
    theme_bw() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position="bottom",
      legend.title = element_blank(),
      # axis.title.x=element_blank(),
      # axis.text.x=element_blank(),
      # axis.ticks.x=element_blank(),
      axis.title.y=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks.y=element_blank()
      )
  
  plot
}  

modify_activity_data <- function(activity_df) {
  
  #######################################################################################################
  #######################################################################################################
  # activity_df[is.na(activity_df)] <- ""
          
  # for (cell in 1:nrow(activity_df)) {
  #   if(activity_df$Reduced_Activity_One[cell]==activity_df$Reduced_Activity_Two[cell]){
  #     #print(cell)
  #       activity_df$Reduced_Activity_Two[cell]=activity_df$Reduced_Activity_Three[cell]
  #       activity_df$Reduced_Activity_Three[cell] = ""
  #       activity_df$Reduced_Activities_QC1[cell]=paste(activity_df$Reduced_Activity_One[cell],
  #                                                      activity_df$Reduced_Activity_Two[cell],
  #                                                      activity_df$Reduced_Activity_Three[cell], sep="+")
  #       activity_df$Reduced_Activities_QC1[cell]<-gsub("(\\+)*$", "", activity_df$Reduced_Activities_QC1[cell])
  #   }
  # 
  #   if ((activity_df$Reduced_Activity_One[cell]=="SA" & activity_df$Reduced_Activity_Two[cell]=="R") | (activity_df$Reduced_Activity_One[cell]=="SA" & activity_df$Reduced_Activity_Two[cell]=="W")){
  #     temp=activity_df$Reduced_Activity_One[cell]
  #     activity_df$Reduced_Activity_One[cell]=activity_df$Reduced_Activity_Two[cell]
  #     activity_df$Reduced_Activity_Two[cell]=temp
  #   }
  # }
  #######################################################################################################
  #######################################################################################################
  
  tab_timeline <- table(activity_df$Reduced_Activities_QC1)
  activity_df<-activity_df[activity_df$Reduced_Activities_QC1 %in% names(tab_timeline)[tab_timeline>60], ]
  
  activity_df$Reduced_Activity_Two[activity_df$Reduced_Activity_Two==""]<-"NA"
  activity_df$Reduced_Activity_Three[activity_df$Reduced_Activity_Three==""]<-"NA"
  
  activity_df$Activity_Two[activity_df$Activity_Two==""]<-"NA"
  activity_df$Activity_Three[activity_df$Activity_Three==""]<-"NA"
  
  activity_df$Reduced_Application_final[activity_df$Reduced_Application_final==""]<-"NA"
  
  activity_df
}

draw_signal_activity_comparison_plots <- function() {
  if (test==T) {
    # subj_list <- c('T001', 'T011', 'T017')
    subj_list <- c('T005')
    day_list <- c('Day1')
    
  } else {
    subj_list <- unique(full_df$Participant_ID)
    # subj_list <- subj_list[-length(subj_list)]
    # subj_list <- c('T019')
    day_list <- unique(full_df$Day)
  }
  
  # print(unique(full_df$Activity_One))
  
  for (subj in subj_list) {
  # for (subj in c('')) {
    subj_df <- full_df %>% filter(Participant_ID==subj)
    
    for (day in day_list) {
      day_df <- subj_df %>% filter(Day==day) 
      
      for (treatment in unique(day_df$Treatment)) {
        
        message(paste(subj, day, treatment))
        
        signal_df <- day_df %>% 
          filter(Treatment==treatment) %>% 
          # select(TreatmentTime, Raw_PP, Raw_E4_EDA, Raw_E4_HR, Raw_iWatch_HR)
          # select(TreatmentTime, Trans_PP, Trans_E4_EDA, Trans_E4_HR, Trans_iWatch_HR)
          select(TreatmentTime, 
                 PP, E4_EDA, E4_HR, iWatch_HR)
          
        melted_df <- melt(signal_df, 'TreatmentTime') 
        # %>%
        #   na.omit()
        
        signal_plot <- ggplot(melted_df, aes(TreatmentTime, value, colour = variable)) + 
          geom_line(size=0.5) +
          geom_point(size=0.5) +
          ggtitle(paste0(subj, ' - ', day, ' - ', treatment)) +
          xlab('Time [s]') +
          ylab('Signal Values') +
          facet_wrap(~ variable, 
                     scales = 'free_y',
                     ncol = 1) +
          scale_colour_discrete() +
          theme_bw() +
          theme(
                panel.grid.major = element_blank(),
                panel.grid.minor = element_blank(),
                axis.line = element_line(colour = "black"),
                plot.title = element_text(hjust = 0.5, size = 16),
                axis.title.x=element_blank(),
                axis.title.y=element_blank(),
                axis.text.y=element_blank(),
                axis.ticks.y=element_blank(),
                legend.position = 'None',
                )
        
        if (treatment=='WS') {
          activity_df <- day_df %>% 
            filter(Treatment==treatment) %>% 
            select(TreatmentTime,
                   
                   Activity_One,
                   Activity_Two,
                   Activity_Three,
                   
                   Reduced_Activities_QC1, 
                   
                   Reduced_Activity_One, 
                   Reduced_Activity_Two, 
                   Reduced_Activity_Three,
                   
                   Reduced_Application_final
                   )
          
          
          #######################################################################################################
          #######################################################################################################
          activity_df <- modify_activity_data(activity_df)
          #######################################################################################################
          #######################################################################################################

          if (show_activity_details==F) {
            activity_plot <- ggplot(activity_df, aes(x=TreatmentTime)) +
              geom_point(aes(y=factor(1), colour=Reduced_Activity_One), shape=15, size=5) +
              geom_point(aes(y=1.12, colour=Reduced_Activity_Two), shape=15, size=5) +
              geom_point(aes(y=1.24, colour=Reduced_Activity_Three), shape=15, size=5) +
              scale_color_manual(values = Ontology_Color, limits = c("R", "W", "Out", "SA", "SP", "I", "NA")) +
              guides(colour = guide_legend(nrow = 1))
            
          } else {
            Ontology_Color <- c(
               "CR" = "darkgreen",
               "CW" = "turquoise1",
               "PR" = "lightseagreen",
               "PW" = "blue",
               "VI" = "orange",
               "PI" = "thistle",
               "EiP" = "slateblue",
               "Out" = "gray80",
               "SP" = "red",
               "T" = "chartreuse",
               "ELD" = "palevioletred1",
               "OB" = "yellow",
               "NA" = "white")

            activity_plot <- ggplot(activity_df, aes(x=TreatmentTime)) +
              geom_point(aes(y=factor(1), colour=Activity_One), shape=15, size=5) +
              geom_point(aes(y=1.12, colour=Activity_Two), shape=15, size=5) +
              geom_point(aes(y=1.24, colour=Activity_Three), shape=15, size=5) +
              scale_color_manual(values = Ontology_Color, limits = c("CW",  "Out", "EiP", "CR", "SP", "T",
                                                                     "VI", "PI", "PW", "ELD", "OB", "PR", "NA")) +
              guides(colour = guide_legend(nrow = 1))
          }
          

          
          
          # Document Apps
          # Utilities Apps
          # Web Browsing Apps
          # Programming Apps
          # Email
          # Virtual Communication Apps
          # Entertaining Apps
          # NA
          app_colors <- c(
               "Document Apps" = "gray80",
               "Utilities Apps" = "turquoise1",
               "Web Browsing Apps" = "yellow",
               "Programming Apps" = "blue",
               "Email" = "orange",
               "Virtual Communication Apps" = "springgreen2",
               "Entertaining Apps" = "slateblue",
               "NA" = "white"
               )
          
          # app_colors <- gg_color_hue(length(unique(activity_df$Reduced_Application_final)))
          # app_colors[unique(activity_df$Reduced_Application_final)=="NA"] <- "white"

          app_usage_plot <- ggplot(activity_df, aes(x=TreatmentTime)) +
            geom_point(aes(y=factor(1), colour=Reduced_Application_final), shape=15, size=5) +
            scale_color_manual(values=app_colors, limits = c(
               "Document Apps",
               "Utilities Apps",
               "Web Browsing Apps",
               "Programming Apps",
               "Email",
               "Virtual Communication Apps",
               "Entertaining Apps",
               "NA"
               )) +
            xlab('Time [s]')


          app_usage_plot <- add_theme(app_usage_plot)
          activity_plot <- add_theme(activity_plot)

          grid_plot <- grid.arrange(signal_plot, activity_plot, app_usage_plot, ncol=1)
          save_plot(file.path(project_dir, plots_dir, activity_plots_dir,
                              paste0(subj, '_', day, '_', treatment)), 
                    grid_plot,
                    14,
                    10
                    )
          
          
        } else {
          print(signal_plot)
        }
        
        
        # print(plot)
        # print('# --------------------------------------------------------------------------- #')
      }
    }
  }
}



# Participant_ID	Day	Treatment	Timestamp	TreatmentTime	Raw_PP	PP	Trans_PP	Raw_E4_EDA	E4_EDA	Trans_E4_EDA	Raw_E4_HR	E4_HR	Trans_E4_HR	Raw_iWatch_HR	iWatch_HR	Trans_iWatch_HR	Activities	Activities_QC1	Activities_QC2	Activity_One	Activity_Two	Activity_Three	Reduced_Activities_QC1	Reduced_Activity_One	Reduced_Activity_Two	Reduced_Activity_Three	Application	Application_QC1	Application_QC2	Reduced_Application_final	Mask
```



<!-- \newpage -->
```{r echo=FALSE, warning = FALSE, message = FALSE}
test <<- F
show_activity_details <<- F

read_data()
draw_signal_activity_comparison_plots()
```




