---
title: "Segmented_data"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(ggpubr)
library(DataCombine)
library(dplyr)
library(reshape2)
library(tidyr)
library(stringr)
library(plyr)
library(ggplot2)
library(dplyr)
library(miceadds)
library(gtools)
library(ggpubr)
library(gvlma)
library(MASS)
library(reshape2)
```

```{r, echo=FALSE}

current_dir <- getwd()
setwd('..')
root_dir <- getwd()
data_dir <- file.path(root_dir, 'curated-data/physiological-data')
# plot_dir <- 'C:/Users/soton/Documents/R/@CPLResearchProjects/Deadline-Stress-Work-Patterns-2020/plots/CaseStudy'
plot_dir <- file.path(root_dir,'plots/CaseStudy')
data_file_name<-'segment_meta_data_df.csv'
curated_data_dir <- file.path(root_dir, 'curated-data/physiological-data')
Data<-read.csv(file.path(data_dir,data_file_name),stringsAsFactors = FALSE)

questionnaire_data_file <- 'Questionnaire Data.csv'
Q_Data <- read.csv(file.path(data_dir,questionnaire_data_file),stringsAsFactors = FALSE)
Q_Data <- Q_Data[,-c(1, 3:34 )]


```

```{r, echo=FALSE}

Data$Segment <- paste0("Seg-",Data$Segment)
Merged_Data<- merge(x = Data, y = Q_Data, by = "Participant_ID")


# file_name='Meta_data_with_psychometric.csv'
# write.csv(Merged_Data,file.path(curated_data_dir, file_name), row.names = FALSE)

Data_to_plot <- melt(Merged_Data[, c(
    'Day',
    'Segment',
    'BreakTime',
    'WorkingTime'
  )])

  
```

```{r, echo=FALSE}

yaxis_title = bquote(paste(' ln(PP) [ ',''^'o','C',''^2,' ]'))

Day_No <- factor(Data_to_plot$Day)
numberOfDay = nlevels(Day_No)
for (j in 1:numberOfDay) {
  Segments_Day <- subset(Data_to_plot, Day == levels(Day_No)[j])
  # Segments_Day<- reorder(Segments_Day$variable)
  
  plot <-
    ggplot(Segments_Day, aes(fill = variable, y = value, x = Segment)) +
    geom_bar(position = "stack", stat = "identity") +
    theme_minimal() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      # plot.title = element_text(hjust = -0.05, vjust=2.12,size = 20, face = "bold", margin=margin(10,0,5,0)),
      legend.title = element_blank(),
      legend.position = 'bottom',
      axis.text.x = element_text(face = "bold", size = 10),
      axis.text.y = element_text(face = "bold", size = 10),
      axis.title.x = element_text(face = "bold", size = 10),
      axis.title.y = element_text(face = "bold", size = 10),
      plot.title = element_text(hjust = 0.5)
    ) + xlab("Segments") + ylab("Time [s]") + ggtitle(levels(Day_No)[j])
  
  print(plot)
  
  Segments_Day <- subset(Data, Day == levels(Day_No)[j])
  
  plot_pp_line <- ggplot(data = Segments_Day) +
    geom_hline(
      aes(yintercept = Mean_Trans_PP, colour = Segment),
      size = 1.5,
      linetype = "dashed"
    ) +
    theme_minimal() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.title = element_blank(),
      legend.position = 'bottom',
      axis.text.y = element_text(face = "bold", size = 10),
      axis.title.y = element_text(face = "bold", size = 10)
    ) + ylab(yaxis_title)
  print(plot_pp_line)
  
  plot_segment = ggarrange(plot, plot_pp_line, nrow = 2, ncol = 1)
  plot_name=paste0(levels(Day_No)[j],".pdf")
  
  
  full_path<-file.path(plot_dir,plot_name,sep="")
  ggsave(full_path, plot_segment, width = 8.5, height = 11, units = "in")
  
}

```

