---
title: "Quality Control Plots"
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering}
output:
  pdf_document: default
  html_document: default
geometry: top=3.5cm, bottom=3cm

#knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path('plots', 'supplementary.pdf')) })
---




```{r echo = FALSE, warning = FALSE, message = FALSE, results='hide'} 
#-------------------------#
#--------LIBRARIES--------#
#-------------------------#
library(dplyr)
library(ggplot2)
library(cowplot)


# library(readr)
# library(tidyverse)
# library(grid)
# library(gridExtra)
# library(ggpubr)
# library(directlabels)
# library(gsubfn)



#-------------------------#
#-----GLOBAL VARIABLES----#
#-------------------------#
## CHANGE this path if needed
script_dir <- getwd()

project_dir <- dirname(script_dir)
setwd(project_dir)



source(file.path(script_dir, 'us-common-functions.R'))

qc_log_file <- file.path(project_dir, log_dir, paste0('quality-control-plot-log-', format(Sys.Date(), format='%m-%d-%y'), '.txt'))
file.create(qc_log_file)


all_subj_data_file_name <- qc0_file_name
session_mean_file_name <- qc0_session_mean_file_name
activity_mean_file_name <- qc0_activity_mean_file_name


# all_subj_data_file_name <- qc1_file_name
# session_mean_file_name <- qc1_session_mean_file_name
# activity_mean_file_name <- qc1_activity_mean_file_name


# signal_list <- c('PP', 'E4_HR', 'E4_EDA', 'iWatch_HR')
# signal_list <- c('iWatch_HR')
``` 


```{r echo=FALSE, warning = FALSE, message = FALSE}
#-------------------------#
#-----   FUNCTIONS    ----#
#-------------------------#

get_y_label <- function(signal) {
  if (signal=='PP') {
    return(bquote(paste('PP [',''^'o','C',''^2,']')))
  } else if (signal=='E4_HR') { 
    return('E4 HR [BPM]') 
  } else if (signal=='E4_EDA') { 
    return(expression(paste('EDA [', mu, 'S]'))) 
  } else if (signal=='iWatch_HR') { 
    return('iWatch HR [BPM]') 
  } 
  
  
  return('Unknown Axis!!!') 
}


get_session_colors <- function(temp_session_mean_df) {
  colors <- NULL 
  if ("RB" %in% temp_session_mean_df$Treatment) { 
    colors <- c(colors, "#000000") 
  } 
  if ("WS" %in% temp_session_mean_df$Treatment) { 
    colors <- c(colors, "#D02827") 
  }
  
  return(colors)
}


get_activity_colors <- function(temp_session_mean_df) {
  colors <- NULL 
  if ("RB" %in% temp_session_mean_df$Treatment) { 
    colors <- c(colors, "#000000") 
  } 
  if ("WS" %in% temp_session_mean_df$Treatment) { 
    if ("Computer Working" %in% temp_session_mean_df$Activities_QC2) {
      colors <- c(colors, "#D02827")
    }
    if ("Other Activities" %in% temp_session_mean_df$Activities_QC2) {
      colors <- c(colors, "#3388FF")
      # colors <- c(colors, "#3CB44B")
    }
  }
  
  return(colors)
}


get_y_limit <- function(col) {
  return(c(min(col, na.rm=T), 
           max(col, na.rm=T)))
}

get_theme <- function() {
  return (
    theme_bw() +
    theme(panel.background=element_rect(fill="NA"), 
          panel.grid.minor=element_line(colour="#E0E0E0"), 
          legend.position='bottom',
          plot.title=element_text(hjust=0.5,
                                    size=14),
          axis.title.x=element_text(size=10,
                                    margin=margin(t=10, r=0, b=10, l=0, unit="pt")), 
          axis.title.y=element_text(size=12))
  )
}


draw_session_based_plots <- function(session_mean_df) {
  # for(subj in levels(factor(session_mean_df$Participant_ID))) {
  for(subj in levels(factor(session_mean_df$Participant_ID))[5]) {
    message('')
    message(subj)
    message('-----------------')
    
    
    temp_subj_session_mean_df <- session_mean_df %>% 
          filter(Participant_ID==subj)
      
    for (signal in signal_list) {
      
      message(paste0(signal, ' --->'))
      
      plot_list <- list()
      for (day in levels(factor(temp_subj_session_mean_df$Day))) {
      # for (day in levels(factor(temp_subj_session_mean_df$Day))[1]) {
        
        message(day)
        
        temp_session_mean_df <- temp_subj_session_mean_df %>% 
          filter(Day==day) %>% 
          select(Treatment, signal) %>% 
          na.omit()
        
        if (nrow(temp_session_mean_df)>0) {
          
  
          
          # plot <- temp_session_mean_df %>%
          #   ggplot(aes(x=1, y=temp_session_mean_df[[signal]], color=Treatment)) +
          #   ggplot(aes(x=1, y=temp_session_mean_df[[signal]])) +
          
          # plot <- all_subj_df %>%
          #   filter(Participant_ID==subj & Day==day) %>%
          #   select(Treatment, TreatmentTime, signal) %>%
          #   na.omit() %>%
          #   ggplot(aes(x=all_subj_df$TreatmentTime, y=temp_session_mean_df[[signal]], color=Treatment))
            
          plot <- ggplot(temp_session_mean_df) + 
            geom_hline(yintercept=temp_session_mean_df[[signal]],
                       linetype="dashed",
            # geom_hline(aes(yintercept=temp_session_mean_df[[signal]], 
            #            linetype=temp_session_mean_df$Treatment),
                       color=get_session_colors(temp_session_mean_df),
                       size=1.5,
                       alpha=0.8) + 
            ggtitle(paste0(subj, ' - ', day)) +
            xlab('Time [s]') +
            ylab(get_y_label(signal)) +
            ylim(get_y_limit(temp_subj_session_mean_df[[signal]])) +
            # scale_linetype_manual(
            #   name = "",
            #   values = c(2,2,2,2),
            #   guide = guide_legend(override.aes=list(color=get_session_colors(temp_session_mean_df)))
            #   ) +
            get_theme()
          
          plot_list[[length(plot_list)+1]] <- plot
          
          
        } else {
          write_log_msg(paste0('Both session data missing for: ', subj, ' - ', day, ' - ', signal), qc_log_file)
        }
      }
      
      if (length(plot_list)>0) {
        grid_plot <- plot_grid(plotlist=plot_list, ncol=2)
        print(grid_plot)
      }
    }
  }
}


draw_activity_based_plots <- function(activity_mean_df) {
  
  for(subj in levels(factor(activity_mean_df$Participant_ID))) {
  # for(subj in levels(factor(activity_mean_df$Participant_ID))[5]) {
    message('')
    message(subj)
    message('-----------------')
    
    
    temp_subj_activity_mean_df <- activity_mean_df %>% 
          filter(Participant_ID==subj)
      
    for (signal in signal_list) {
      
      message(paste0(signal, ' --->'))
      
      plot_list <- list()
      for (day in levels(factor(temp_subj_activity_mean_df$Day))) {
      # for (day in levels(factor(temp_subj_activity_mean_df$Day))[1]) {
        
        message(day)
        
        temp_activity_mean_df <- temp_subj_activity_mean_df %>% 
          filter(Day==day) %>% 
          select(Treatment, Activities_QC2, signal) %>% 
          na.omit()
        
        if (nrow(temp_activity_mean_df)>0) {
          
          # plot <- temp_activity_mean_df %>%
          #   ggplot(aes(x=1, y=temp_activity_mean_df[[signal]], color=Activities_QC2)) +
          
          # plot <- all_subj_df %>%
          #   filter(Participant_ID==subj & Day==day) %>%
          #   select(Treatment, TreatmentTime, signal) %>%
          #   na.omit() %>%
          #   ggplot(aes(x=all_subj_df$TreatmentTime, y=temp_session_mean_df[[signal]], color=Treatment))
            
          plot <- ggplot(temp_activity_mean_df) +
            ggtitle(paste0(subj, ' - ', day)) +
            geom_hline(yintercept=temp_activity_mean_df[[signal]],
                       linetype="dashed",
           # geom_hline(aes(yintercept=temp_activity_mean_df[[signal]], 
           #             linetype=temp_activity_mean_df$Treatment),
                       color=get_activity_colors(temp_activity_mean_df), 
                       size=1.5,
                       alpha=0.8) + 
            xlab('Time [s]') +
            ylab(get_y_label(signal)) +
            ylim(get_y_limit(temp_subj_activity_mean_df[[signal]])) +
            # scale_linetype_manual(
            #   name = "",
            #   values = c(2,2,2,2),
            #   guide = guide_legend(override.aes=list(color=get_activity_colors(temp_activity_mean_df)))
            #   ) +
            get_theme()
          
          plot_list[[length(plot_list)+1]] <- plot
          
        } else {
          # write_log_msg(paste0('Both session data missing for: ', subj, ' - ', day, ' - ', signal), qc_log_file)
        }
      }
      
      if (length(plot_list)>0) {
        grid_plot <- plot_grid(plotlist=plot_list, ncol=2)
        print(grid_plot)
      }
    }
  }
  
}



draw_plots <- function() {
  
  # all_subj_df <- custom_read_csv(file.path(project_dir, curated_data_dir, physiological_data_dir, all_subj_data_file_name))
  session_mean_df <- custom_read_csv(file.path(project_dir, curated_data_dir, physiological_data_dir, session_mean_file_name))
  activity_mean_df <- custom_read_csv(file.path(project_dir, curated_data_dir, physiological_data_dir, activity_mean_file_name))
  
  # draw_session_based_plots(all_subj_df, session_mean_df)
  # draw_activity_based_plots(all_subj_df, activity_mean_df)
  
  draw_session_based_plots(session_mean_df)
  draw_activity_based_plots(activity_mean_df)
}



```



\newpage
<!-- DRAW PLOTS -->
```{r echo=FALSE, warning = FALSE, message = FALSE, fig.height=10, fig.width=12}
draw_plots()
```






```{r echo=FALSE, warning = FALSE, message = FALSE}
# mean_line_day1<-function(df, name){
#    plot<-ggplot(df)+
#    geom_hline(aes(yintercept=df$x[1],linetype="Baseline"),size=1, color="black" )+
#    geom_hline(aes(yintercept=df$x[2],linetype="WorkingSession"),size=1, color="orange" )+
#
#    scale_linetype_manual(name = "",
#                          values = c(2,2,2,2),
#                          guide = guide_legend(override.aes = list(color = c("black", "orange"))))+
#      theme_bw()+
#      theme(legend.position = "bottom")+theme(legend.title = element_blank())+
#      labs(title=name , x="Time", y=bquote(paste('Perinasal Perspiration [',''^'o','C',''^2,']')))+
#      theme(plot.title = element_text(hjust = 0.5))+
#      ylim(0.0030,0.0070)
#    return (plot)
# }
```
